#!/usr/bin/env python3
"""Generate the TikZ mesh-icon for the meshio++ logo: the Stanford Bunny.

Reads ``example/Bunny.stl`` ("Stanford Bunny -- Digitized!" by MakerBot,
CC-BY, https://www.thingiverse.com/thing:88208) with meshio++ itself,
decimates it to a logo-friendly triangle count with PyVista, projects it
through meshio++'s own 3D rendering machinery (`meshioplusplus._projection`
-- the orthographic isometric camera + painter's-algorithm depth sort that
powers the SVG/TikZ writers for 3D meshes), and emits the faces as TikZ
``\\draw[fill=...]`` commands into ``_mesh_icon.tex`` (which ``logo.tex``
and ``logo-icon.tex`` ``\\input``). Every face is coloured with the same
blue->teal gradient as the previous "FE blob" logo (a faux finite-element
field over the bunny), with white mesh edges.

Deterministic: quadric decimation and the projection carry no randomness,
so re-running reproduces the same logo byte-for-byte. Requires meshio++
(this repo's venv) + numpy + pyvista.

Run from anywhere::

    python gen_logo_tikz.py            # writes logo/_mesh_icon.tex

then compile with ``build.sh``.
"""

from __future__ import annotations

import os
import tempfile

import numpy as np
import pyvista as pv

import meshioplusplus
from meshioplusplus._projection import ISO_AZIMUTH, ISO_ELEVATION, project_surface

HERE = os.path.dirname(os.path.abspath(__file__))
BUNNY = os.path.join(HERE, "..", "..", "example", "Bunny.stl")
OUT = os.path.join(HERE, "_mesh_icon.tex")

# Palette (RGB 0-255): deep blue -> bright teal, as before.
BLUE = np.array([31, 78, 121], dtype=float)
TEAL = np.array([46, 196, 182], dtype=float)
EDGE = "white"
EDGE_WIDTH = "0.25pt"

TARGET_FACES = 900  # logo-friendly decimation target
ICON_SIZE = 2.5  # cm, bounding box of the icon


def load_decimated_bunny() -> meshioplusplus.Mesh:
    """The bunny as a meshio++ triangle mesh, decimated to ~TARGET_FACES."""
    mesh = meshioplusplus.read(BUNNY)
    conn = mesh.get_cells_type("triangle").astype(np.int64)
    faces = np.hstack([np.full((len(conn), 1), 3, dtype=np.int64), conn]).ravel()
    poly = pv.PolyData(np.asarray(mesh.points, dtype=float), faces)
    dec = poly.decimate(1.0 - TARGET_FACES / len(conn))
    dec_conn = dec.faces.reshape(-1, 4)[:, 1:]
    return meshioplusplus.Mesh(np.asarray(dec.points), [("triangle", dec_conn)])


def tri_colour(height_norm: float) -> tuple[int, int, int]:
    """Interpolate blue->teal by normalised projected height."""
    c = BLUE + (TEAL - BLUE) * height_norm
    return tuple(int(round(v)) for v in c)


def main() -> None:
    bunny = load_decimated_bunny()

    # Smoke-check the real writer path once: the TikZ writer must accept the
    # 3D bunny directly (it uses the same projection machinery as below).
    with tempfile.TemporaryDirectory() as tmp:
        meshioplusplus.tikz.write(os.path.join(tmp, "bunny.tikz"), bunny)

    # Project with the CAD-isometric camera, rotated 180 degrees about the
    # z axis so the bunny faces left, and paint back-to-front.
    x, y, faces = project_surface(bunny, ISO_AZIMUTH + 180.0, ISO_ELEVATION, 0.0)

    # Fit into a centred [0, ICON_SIZE]^2 box, preserving the aspect ratio.
    min_x, max_x = float(np.min(x)), float(np.max(x))
    min_y, max_y = float(np.min(y)), float(np.max(y))
    span = max(max_x - min_x, max_y - min_y)
    scale = ICON_SIZE / span
    px = (x - (min_x + max_x) / 2.0) * scale + ICON_SIZE / 2.0
    py = (y - (min_y + max_y) / 2.0) * scale + ICON_SIZE / 2.0

    lines = [
        "% Auto-generated by gen_logo_tikz.py -- do not edit by hand.",
        "% Stanford Bunny ('Stanford Bunny -- Digitized!' by MakerBot, CC-BY,",
        "% thingiverse.com/thing:88208), decimated and rendered through",
        "% meshio++'s own 3D skin projection (isometric camera, painter's",
        "% algorithm), coloured with a blue->teal faux-FE field.",
        "\\begin{scope}",
    ]

    # Screen-space height of each face centroid drives the colour ramp.
    heights = np.array([py[nodes].mean() for nodes, _, _ in faces])
    lo, hi = float(heights.min()), float(heights.max())

    # One fill+stroke per face, in back-to-front order (nearer faces cover
    # the hidden edges of farther ones).
    for (nodes, _, _), h in zip(faces, heights):
        hn = (h - lo) / (hi - lo) if hi > lo else 0.5
        r, g, b = tri_colour(float(hn))
        coords = " -- ".join(f"({px[i]:.4f},{py[i]:.4f})" for i in nodes)
        lines.append(
            f"  \\draw[line width={EDGE_WIDTH},draw={EDGE},"
            f"fill={{rgb,255:red,{r};green,{g};blue,{b}}}] {coords} -- cycle;"
        )
    lines.append("\\end{scope}")
    lines.append("")

    with open(OUT, "w") as fh:
        fh.write("\n".join(lines))

    print(f"wrote {OUT}: {len(faces)} triangles, {len(px)} vertices")


if __name__ == "__main__":
    main()
