name = "MeshioPlusPlus"
uuid = "e7ab4aca-eb60-4871-ac29-9ed1ef292e46"
authors = ["Vicente Mataix Ferrándiz <tote1989@gmail.com>"]
version = "10.15.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
