// Auto-generated by CAD-Preview. Edits here are not read back by the
// extension; use the Meshing panel to change options.
Merge "1797609in.stp";
Mesh.MeshSizeMin = 0;
Mesh.MeshSizeMax = 0.03102946407042117;
Mesh.Algorithm = 6;
Mesh.Algorithm3D = 4;
Mesh.ElementOrder = 1;
Mesh.RecombineAll = 0;
Mesh.SubdivisionAlgorithm = 0;
Mesh.Optimize = 1;
Mesh 3;
