# usage:
#    tox          --> default, runs pytest
#    tox -e fmt   --> format the code and README
#    tox -e lint  --> check code formatting and lint the code

[tox]
envlist = py39, py312
isolated_build = True

[pytest]
markers =
    viewer: needs the optional polyscope backend and a GL runtime (see doc/viewer.md)

[testenv]
deps =
    pytest
    pytest-codeblocks >= 0.12.1
    pytest-cov
    h5py
    netCDF4; sys_platform != "win32" or python_version != "3.8"
# extras = all
commands =
    pytest {posargs} --codeblocks

[testenv:fmt]
skip_install = True
commands =
    isort .
    black .
    blacken-docs README.md
deps =
    black
    isort
    blacken-docs

[testenv:lint]
skip_install = True
commands =
    isort --check .
    black --check .
    flake8 .
deps =
    black
    flake8
    isort
