// Ergonomic wrapper around the raw Emscripten/embind glue generated by
// bindings/wasm/js_bindings.cpp (see ../../../CMakeLists.txt's `if(EMSCRIPTEN)`
// block and ../../../build/configure-wasm.sh). The raw glue (dist/
// meshioplusplus_wasm.mjs, built by CMake, not hand-written) exports a
// MODULARIZE=1 + EXPORT_ES6=1 factory function; this file wraps that
// factory so callers get:
//   - default parameters (`format = ''` to infer from the file extension,
//     matching the C++ side's `resolve_format`, instead of Emscripten's raw
//     embind functions which require every parameter explicitly);
//   - a `convert()` with a friendlier `{ inFormat, outFormat }` options bag
//     instead of two trailing positional strings;
//   - `Module.FS` passed through unwrapped, since virtual-filesystem access
//     is the one place this package intentionally stays close to the raw
//     Emscripten API (see the README's "Reading/writing files" section).
//
// Each call to loadMeshioPlusPlus() instantiates a fresh, independent WASM
// module instance (safe to call more than once, e.g. one per Web Worker).
//
// The package ships TWO native artifacts and picks one at load time:
//   - meshioplusplus_wasm      the sequential build (always loadable);
//   - meshioplusplus_wasm_mt   the threaded build (OpenMP over Wasm threads =
//                              pthreads/SharedArrayBuffer), which is faster for
//                              the mesh operations but only loads where the page
//                              is *cross-origin isolated* (COOP `same-origin` +
//                              COEP `require-corp`); it aborts on instantiation
//                              otherwise, with no in-artifact fallback.
// resolveVariant() below chooses: the threaded build under Node (where
// SharedArrayBuffer is always available) and in a cross-origin-isolated browser
// context, else the sequential one. The dynamic import()s are literal so
// bundlers (Vite) emit both chunks. Callers can force a build with the
// `{ variant }` option.

// The raw xdmfSeriesWriteDataArrays embind call still converts every value
// with emscripten::convertJSArrayToNumberVector<double>, which throws on a
// BigInt64Array/BigUint64Array element (a JS `bigint` does not implicitly
// convert to `double`). Since data arrays now carry their source dtype
// (point_data/cell_data read off a mesh may be BigInt-backed), widen those to
// plain Float64-representable arrays here rather than in every caller.
function toDoubleConvertible(rArr) {
    return rArr instanceof BigInt64Array || rArr instanceof BigUint64Array
        ? Array.from(rArr, Number)
        : rArr;
}

function widenBigIntArrays(rObj) {
    const out = {};
    for (const [name, arr] of Object.entries(rObj)) out[name] = toDoubleConvertible(arr);
    return out;
}

/**
 * Decide which native artifact to load.
 * @param {'auto'|'mt'|'seq'} variant
 * @returns {'mt'|'seq'}
 */
function resolveVariant(variant) {
    if (variant === 'mt' || variant === 'seq') return variant;
    // `crossOriginIsolated` is a browser global; it is `undefined` under Node,
    // where Wasm threads (worker_threads + SharedArrayBuffer) always work.
    if (typeof crossOriginIsolated === 'undefined') return 'mt';
    return crossOriginIsolated ? 'mt' : 'seq';
}

/**
 * Thrown by `loadMeshioPlusPlus()` when a WASM module fails to instantiate,
 * so a caller can tell a wrong `.wasm` URL from an environment that cannot
 * run Wasm threads from a plain network failure, instead of catching a bare
 * Emscripten abort. See doc/wasm.md's "Loading" section.
 */
export class MeshioPlusPlusLoadError extends Error {
    /**
     * @param {string} message
     * @param {object} details
     * @param {'mt'|'seq'} details.variant - which artifact was being loaded.
     * @param {string} details.glue - the glue module specifier (e.g.
     *   '../dist/meshioplusplus_wasm_mt.mjs').
     * @param {string} [details.requestedFile] - the filename Emscripten asked
     *   `locateFile` to resolve, if it got that far.
     * @param {string} [details.resolvedUrl] - what `locateFile` returned for it.
     * @param {unknown} [details.cause] - the underlying error/abort reason.
     */
    constructor(message, { variant, glue, requestedFile, resolvedUrl, cause }) {
        super(message, cause === undefined ? undefined : { cause });
        this.name = 'MeshioPlusPlusLoadError';
        this.variant = variant;
        this.glue = glue;
        this.requestedFile = requestedFile;
        this.resolvedUrl = resolvedUrl;
        this.cause = cause;
    }
}

/**
 * A rectangular (uniform node count) group of cells.
 * @typedef {Object} RectangularCellBlock
 * @property {string} type - meshio++ cell type name (e.g. "triangle", "tetra10").
 * @property {Int32Array} data - flat, row-major connectivity (numCells * nodesPerCell).
 * @property {number} nodesPerCell
 */

/**
 * A 1-level ragged (jagged polygon) block: rows of varying node count, so
 * there is no single `nodesPerCell`. Two flat CSR arrays instead of a nested
 * array of arrays, which embind has no efficient representation for.
 * @typedef {Object} PolygonCellBlock
 * @property {string} type
 * @property {Int32Array} data - every row's node ids concatenated.
 * @property {Int32Array} rowOffsets - each cell's start in `data` (numCells + 1).
 */

/**
 * A 2-level ragged (polyhedron) block: each cell a list of faces, each face a
 * list of node ids.
 * @typedef {Object} PolyhedronCellBlock
 * @property {string} type
 * @property {Int32Array} data - every face's node ids concatenated.
 * @property {Int32Array} faceOffsets - each face's start in `data` (totalFaces + 1).
 * @property {Int32Array} cellOffsets - each cell's start in the face list (numCells + 1).
 */

/**
 * One homogeneous group of cells. Which shape it is is told by key presence:
 * `cellOffsets` means polyhedron, `rowOffsets` means polygon, `nodesPerCell`
 * means rectangular. See doc/polyhedra.md.
 * @typedef {RectangularCellBlock | PolygonCellBlock | PolyhedronCellBlock} CellBlock
 */

/**
 * @typedef {Object} XdmfTimeSeriesWriter
 * @property {(mesh: Mesh) => void} writePointsCells - the static grid, once.
 * @property {(time: number, mesh: Mesh) => void} writeData - one step's data.
 * @property {(time: number, pointData: Object<string, Float64Array>, cellData?: Object<string, Float64Array>, components?: Object<string, number>) => void} writeDataArrays - one step from raw arrays.
 * @property {() => void} flush - write the `.xdmf` as it stands, without finalizing.
 * @property {() => void} finalize - write the `.xdmf`; idempotent.
 * @property {() => number} numSteps
 * @property {() => boolean} finalized
 * @property {() => void} close - finalize (if needed) and release the handle.
 */

/**
 * A single sequence entry: one step of one file. See {@link SequenceReader}.
 * @typedef {Object} SequenceEntry
 * @property {string} path
 * @property {number} step
 * @property {number} time
 * @property {'explicit'|'file'|'filename'|'index'} timeSource
 */

/**
 * @typedef {Object} SequenceReader
 * @property {number} count
 * @property {(i: number) => string} path
 * @property {(i: number) => number} step
 * @property {(i: number) => number} time
 * @property {(i: number) => ('explicit'|'file'|'filename'|'index')} timeSource
 * @property {(i: number) => SequenceEntry} entry
 * @property {() => SequenceEntry[]} entries
 * @property {(i: number, options?: {pointsOnly?: boolean, arrays?: string[]|null, lenient?: boolean}) => Mesh} read
 * @property {() => void} close - release the handle; safe to call twice.
 */

/**
 * A point_data/cell_data/field_data array's JS type: it carries its source
 * dtype crossing the WASM boundary rather than always widening to
 * Float64Array (dtype carry, v11.2.0).
 * @typedef {Float32Array|Float64Array|Int8Array|Int16Array|Int32Array|BigInt64Array|Uint8Array|Uint16Array|Uint32Array|BigUint64Array} DataArray
 */

/**
 * @typedef {Object} Mesh
 * @property {Float64Array} points - flat, row-major (numPoints * dim).
 * @property {number} dim - 2 or 3.
 * @property {CellBlock[]} cells
 * @property {Object<string, DataArray>} [point_data]
 * @property {Object<string, number>} [point_data_components] - per-entity width of any non-scalar point_data array, since a flat typed array carries no shape; absent name = 1 component.
 * @property {Object<string, DataArray[]>} [cell_data] - one array per cell block, same order as `cells`; every block of one named array shares the same DataArray class.
 * @property {Object<string, number>} [cell_data_components] - per-entity width of any non-scalar cell_data array (one value per array, not per block).
 * @property {Object<string, DataArray>} [field_data]
 * @property {Object<string, number>} [field_data_components] - per-entity width of any non-scalar field_data array.
 * @property {Array<{name: string, kind: string, dim: number, tag: number, entries: Int32Array}>} [regions] - named point/cell/side groups, see doc/regions.md.
 * @property {Array<{id: number, values: Array<{key: string, values: Float64Array, text: string, isTable: boolean, components?: number}>}>} [propertySets] - `Begin Properties` blocks (currently MDPA only), see doc/wasm.md.
 */

/**
 * Instantiate a fresh meshio++ WASM module.
 *
 * @param {object} [moduleOverrides] - forwarded to the Emscripten module
 *   factory (with `locateFile`/`onAbort` wrapped for diagnostics -- see
 *   {@link MeshioPlusPlusLoadError} -- your own overrides still run first).
 *   `{ locateFile: (p) => new URL(p, import.meta.url) }` relocates the
 *   `.wasm` binary for a bundler/CDN setup; `locateFile` receives the
 *   requested filename, so return the URL matching the loaded variant
 *   (`meshioplusplus_wasm.wasm` or `_wasm_mt.wasm`).
 * @param {object} [options]
 * @param {'auto'|'mt'|'seq'} [options.variant='auto'] - which native artifact to
 *   load. `auto` picks the threaded (`mt`) build under Node and in a
 *   cross-origin-isolated browser, else the sequential (`seq`) build; `mt`/`seq`
 *   force one (`mt` aborts if the environment cannot host Wasm threads).
 * @returns {Promise<{
 *   FS: object,
 *   readMesh: (path: string, format?: string) => Mesh,
 *   readMeshSelective: (path: string, options?: {format?: string, pointsOnly?: boolean, arrays?: string[], timeStep?: number, lenient?: boolean, piece?: number, info?: boolean}) => Mesh,
 *   readMetadata: (path: string, format?: string) => object,
 *   readerSupportsOptions: (format: string) => boolean,
 *   writeMesh: (path: string, mesh: Mesh, format?: string, options?: {encoding?: string, codec?: string, floatFormat?: string, info?: object}) => string[],
 *   convert: (inPath: string, outPath: string, options?: {inFormat?: string, outFormat?: string, encoding?: string, codec?: string, floatFormat?: string}) => string[],
 *   convertSurface: (inPath: string, outPath: string, options?: {inFormat?: string, outFormat?: string}) => void,
 *   convertSurfaceOps: (inPath: string, outPath: string, ops?: object[], options?: {inFormat?: string, outFormat?: string, keepProvenance?: boolean}) => {steps: object[], warnings: string[]},
 *   runPipeline: (settings: object|string) => {steps: object[], warnings: string[]},
 *   sequenceEntries: (source: string|string[], options?: object) => object[],
 *   sequenceToTimeseries: (source: string|string[], outPath: string, outFormat?: string, options?: object) => number,
 *   timeseriesToSequence: (inPath: string, outPattern: string, inFormat?: string, outFormat?: string) => string[],
 *   numNodesPerCell: () => Object<string, number>,
 *   topologicalDimension: () => Object<string, number>,
 *   meshBackend: () => string,
 *   parallelBackend: () => string,
 *   hasCgnslib: () => boolean,
 *   availableFormats: () => {readers: string[], writers: string[]},
 *   extractSurface: (mesh: Mesh, recordParentIds?: boolean) => Mesh,
 *   extractSkin: (mesh: Mesh, linearize?: boolean) => Mesh,
 *   attachQuality: (mesh: Mesh) => Mesh,
 *   sniffFormat: (path: string) => string,
 *   reorder: (mesh: Mesh, method?: string) => object,
 *   computeBandwidth: (mesh: Mesh) => number,
 *   diff: (a: Mesh, b: Mesh, atol?: number, rtol?: number, unordered?: boolean) => object,
 *   meshesEqual: (a: Mesh, b: Mesh, atol?: number, rtol?: number, unordered?: boolean) => boolean,
 *   merge: (meshes: Mesh[], weld?: boolean, atol?: number, sourceTag?: boolean, dataPolicy?: string, dropDuplicateCells?: boolean, returnMaps?: boolean) => Mesh | {mesh: Mesh, pointMaps: Int32Array[], cellMaps: Int32Array[]},
 *   transform: (mesh: Mesh, matrix: number[], rotateVectorData?: boolean) => Mesh,
 *   clean: (mesh: Mesh, weld?: boolean, atol?: number, removeOrphans?: boolean, dropDegenerate?: boolean, dropDuplicateCells?: boolean, returnMaps?: boolean) => {mesh: Mesh, pointsWelded: number, pointsRemovedOrphan: number, cellsDroppedDegenerate: number, cellsDroppedDuplicate: number, pointMap?: Int32Array, cellMaps?: Int32Array[]},
 *   smooth: (mesh: Mesh, method?: string, iterations?: number, lambda?: number, mu?: number, fixBoundary?: boolean, preserveFeatures?: boolean, featureAngle?: number, guardInversion?: boolean, frozen?: number[]|Int32Array|null) => {mesh: Mesh, numNodesMoved: number, maxDisplacement: number, numSkippedInversion: number},
 *   interpolate: (source: Mesh, target: Mesh, method?: string, arrays?: string[], extrapolate?: boolean, defaultValue?: number, onConflict?: string) => Mesh,
 *   conservativeInterpolate: (source: Mesh, target: Mesh, arrays?: string[], defaultValue?: number, onConflict?: string) => Mesh,
 *   undoGreen: (coarse: Mesh, fine: Mesh) => {mesh: Mesh, numGroupsUndone: number, numCellsRemoved: number},
 *   cropBbox: (mesh: Mesh, lo: number[], hi: number[], mode?: string, recordIds?: boolean, returnMaps?: boolean) => Mesh | {mesh: Mesh, pointMap: Int32Array, cellMaps: Int32Array[]},
 *   cropPlane: (mesh: Mesh, point: number[], normal: number[], mode?: string, recordIds?: boolean, returnMaps?: boolean) => Mesh | {mesh: Mesh, pointMap: Int32Array, cellMaps: Int32Array[]},
 *   cropPredicate: (mesh: Mesh, array: string, compare?: string, value?: number, recordIds?: boolean, returnMaps?: boolean) => Mesh | {mesh: Mesh, pointMap: Int32Array, cellMaps: Int32Array[]},
 *   slice: (mesh: Mesh, origin: number[], normal: number[], recordParentIds?: boolean) => Mesh,
 *   isosurface: (mesh: Mesh, array: string, isovalues: number|number[], component?: number, recordParentIds?: boolean) => Mesh,
 *   grid: (dims: number[], origin?: number[], spacing?: number[], maxCells?: number) => Mesh,
 *   voxelize: (mesh: Mesh, resolution?: number[], cellSize?: number, bounds?: number[], padding?: number, paddingRelative?: number, fill?: string, sign?: string, attachOccupancy?: boolean, maxCells?: number, watertightCheck?: string) => {mesh: Mesh, dims: number[], origin: number[], spacing: number[], numOccupied: number},
 *   surfaceWatertightCheck: (mesh: Mesh) => {boundaryEdges: number, nonManifoldEdges: number, inconsistentPairs: number, degenerateTriangles: number, watertight: boolean},
 *   sampleDistance: (surface: Mesh, points: number[], sign?: string, band?: number, watertightCheck?: string) => Float64Array,
 *   distanceToSurface: (query: Mesh, surface: Mesh, sign?: string, location?: string, band?: number, recordInside?: boolean, watertightCheck?: string) => {mesh: Mesh, numBanded: number, quality: object},
 *   computeSdf: (surface: Mesh, structure?: string, resolution?: number[], cellSize?: number, bounds?: number[], padding?: number, paddingRelative?: number, rootResolution?: number, maxDepth?: number, bandCells?: number, recordLevels?: boolean, maxCells?: number, sign?: string, location?: string, band?: number, watertightCheck?: string) => {mesh: Mesh, dims: number[], origin: number[], spacing: number[], maxDepth: number, numBanded: number, quality: object},
 *   gradient: (mesh: Mesh, array: string, operator?: string, method?: string, location?: string, output?: string, component?: number, overwrite?: boolean) => {mesh: Mesh, numSkipped: number, numFallback: number},
 *   hessian: (mesh: Mesh, array: string, method?: string, location?: string, output?: string, overwrite?: boolean) => {mesh: Mesh, numSkipped: number, numFallback: number},
 *   estimateError: (mesh: Mesh, array: string, method?: string, marking?: string, markingValue?: number, output?: string, marked?: string, overwrite?: boolean) => {mesh: Mesh, globalError: number, numSkipped: number, numMarked: number},
 *   remesh: (mesh: Mesh, numClusters: number, subdivide?: number, subsampleRatio?: number, maxSubdivide?: number, maxIterations?: number, maxRepairPasses?: number, metric?: string, gradation?: number, preserveBoundary?: boolean, maxAnisotropy?: number) => {mesh: Mesh, numClusters: number, numIterations: number, subdivideApplied: number, numIsolatedClusters: number, numNonManifoldVertices: number},
 *   remeshVolume: (mesh: Mesh, resolution?: number[], cellSize?: number, bounds?: number[], padding?: number, paddingRelative?: number, maxCells?: number, maxTets?: number, warpFraction?: number, sign?: string, watertightCheck?: string) => {mesh: Mesh, numTets: number, numVerticesWarped: number, numTetsRejected: number, numNonManifoldEdges: number},
 *   optimizeVolume: (mesh: Mesh, maxIterations?: number, relocate?: boolean, flip?: boolean, preserveBoundary?: boolean, minImprovement?: number) => {mesh: Mesh, numFlips: number, num23Flips: number, num32Flips: number, numVerticesMoved: number, numTets: number, minQualityBefore: number, minQualityAfter: number},
 *   computeCurvature: (mesh: Mesh, mean?: boolean, gaussian?: boolean, dualArea?: string, includeBoundary?: boolean, recordArea?: boolean, recordPrincipal?: boolean, region?: string) => {mesh: Mesh, numBoundary: number, numIsolated: number, numDegenerate: number, totalAngleDefect: number, quality: {boundaryEdges: number, nonManifoldEdges: number, inconsistentPairs: number, degenerateTriangles: number, watertight: boolean}},
 *   repair: (mesh: Mesh, fixOrientation?: boolean, orientOutward?: boolean, fillHoles?: boolean, splitNonManifold?: boolean, maxHoleEdges?: number, weldTolerance?: number, recordProvenance?: boolean) => {mesh: Mesh, qualityBefore: object, qualityAfter: object, numFlipped: number, numComponents: number, largestComponent: number, numOrientedOutward: number, numUnorientable: number, numVerticesSplit: number, numHolesDetected: number, numHolesFilled: number, numHolesSkipped: number, numFacesAdded: number, numPointsAdded: number, pointsWelded: number},
 *   shrinkwrap: (mesh: Mesh, target: Mesh, offset?: number, maxDistance?: number, weights?: string, targetRegion?: string, normalWeight?: string, recordDistance?: boolean, recordClosestCell?: boolean) => {mesh: Mesh, quality: object, numProjected: number, numMissed: number, numSkipped: number, maxDisplacement: number},
 *   sobolevDeform: (mesh: Mesh, array: string, lengthScale: number, fixedPointsArray?: string, fixBoundary?: boolean, recordFiltered?: boolean, maxIterations?: number, tolerance?: number) => {mesh: Mesh, numIterations: number, residual: number, converged: boolean, numFixed: number, numIsolated: number, maxDisplacement: number},
 *   split: (mesh: Mesh, by: string, tagName?: string, returnMaps?: boolean) => {key: string, mesh: Mesh, pointMap?: Int32Array, cellMaps?: Int32Array[]}[],
 *   convertCells: (mesh: Mesh, mode?: string, recordParentIds?: boolean, returnMaps?: boolean) => Mesh | {mesh: Mesh, pointMap: Int32Array, cellMaps: Int32Array[]},
 *   subdivide: (mesh: Mesh, recordParentIds?: boolean, returnMaps?: boolean) => Mesh | {mesh: Mesh, cellMaps: Int32Array[]},
 *   agglomerate: (mesh: Mesh, targetGroupSize?: number, returnMaps?: boolean) => Mesh | {mesh: Mesh, cellMap: Int32Array},
 *   refine: (mesh: Mesh, levels?: number, recordParentIds?: boolean,
 *            options?: object, returnMaps?: boolean) => Mesh | {mesh: Mesh, pointMap: Int32Array, cellMaps: Int32Array[]},
 *   decimate: (mesh: Mesh, ratio?: number, targetFaces?: number, maxError?: number, placement?: string, preserveBoundary?: boolean, preserveFeatures?: boolean, featureAngle?: number, frozen?: number[]|Int32Array|null, returnMaps?: boolean) => {mesh: Mesh, facesRemoved: number, pointsRemoved: number, collapsesRejected: number, maxErrorApplied: number, pointMap?: Int32Array, cellMaps?: Int32Array[]},
 *   decimateVolume: (mesh: Mesh, ratio?: number, targetCells?: number, maxError?: number, placement?: string, preserveBoundary?: boolean, preserveFeatures?: boolean, featureAngle?: number, frozen?: number[]|Int32Array|null, returnMaps?: boolean) => {mesh: Mesh, tetsRemoved: number, pointsRemoved: number, collapsesRejected: number, maxErrorApplied: number, pointMap?: Int32Array, cellMaps?: Int32Array[]},
 *   partition: (mesh: Mesh, nparts: number, method?: string, imbalance?: number, mode?: string, seed?: number, recordIds?: boolean, ghostLayers?: number, weightsKey?: string, returnMaps?: boolean) => {partId: number, mesh: Mesh, pointMap?: Int32Array, cellMaps?: Int32Array[]}[],
 *   partitionLabels: (mesh: Mesh, nparts: number, method?: string, imbalance?: number, mode?: string, seed?: number, weightsKey?: string) => number[][],
 *   stats: (mesh: Mesh) => object,
 *   withProvenance: <T>(mode: number|null|undefined, fn: () => T) => T,
 *   provenanceBegin: (mode?: number) => void,
 *   provenanceEnd: () => void,
 *   provenanceNote: (category: string, detail: string) => void,
 *   provenanceSetSource: (path: string, format: string) => void,
 *   provenanceSetTarget: (format: string, encoding?: string, codec?: string, floatFormat?: string) => void,
 *   readProvenance: (path: string) => {lines: string[], recognised: boolean},
 *   dataDrop: (mesh: Mesh, location: string, names?: string[], ignoreMissing?: boolean) => Mesh,
 *   dataKeep: (mesh: Mesh, location: string, names?: string[], ignoreMissing?: boolean) => Mesh,
 *   dataRename: (mesh: Mesh, location: string, from: string, to: string) => Mesh,
 *   dataPointToCell: (mesh: Mesh, names?: string[], suffix?: string) => Mesh,
 *   dataCellToPoint: (mesh: Mesh, names?: string[], weight?: string, suffix?: string) => Mesh,
 *   dataCalc: (mesh: Mesh, expression: string, location: string, outputName: string, overwrite?: boolean) => Mesh,
 *   dataCondition: (mesh: Mesh, location: string, names?: string[], mode?: string, lo?: number, hi?: number, scope?: string, nanPolicy?: string, nanReplacement?: number, suffix?: string) => Mesh,
 *   dataInfo: (mesh: Mesh) => object[],
 *   dataIntegrate: (mesh: Mesh, arrays?: string[]) => object[],
 *   createXdmfTimeSeriesWriter: (path: string, options?: {dataFormat?: string, gzipLevel?: number, mode?: 'truncate'|'append', autoFlush?: boolean}) => XdmfTimeSeriesWriter,
 *   openSequence: (source: string|string[], options?: object) => SequenceReader,
 * }>}
 * @throws {MeshioPlusPlusLoadError} if the WASM module fails to instantiate.
 */
export async function loadMeshioPlusPlus(moduleOverrides = {}, { variant = 'auto' } = {}) {
    const chosen = resolveVariant(variant);
    const glue =
        chosen === 'mt' ? '../dist/meshioplusplus_wasm_mt.mjs' : '../dist/meshioplusplus_wasm.mjs';
    // Literal specifiers so bundlers emit both chunks; the sequential one is
    // the fallback whenever threads are unavailable.
    const { default: createRawModule } =
        chosen === 'mt'
            ? await import('../dist/meshioplusplus_wasm_mt.mjs')
            : await import('../dist/meshioplusplus_wasm.mjs');

    // Wrap locateFile/onAbort (rather than passing moduleOverrides through
    // untouched) so a failed instantiation can be reported with which file
    // Emscripten actually asked for and what locateFile resolved it to,
    // instead of a bare Emscripten abort message. onAbort is overridden even
    // though the try/catch below is the primary path, because an abort under
    // Node does not always surface as a catchable rejection in every
    // Emscripten build -- this guarantees the reason is captured regardless.
    const userLocateFile = moduleOverrides.locateFile;
    const userOnAbort = moduleOverrides.onAbort;
    let requestedFile;
    let resolvedUrl;
    let abortReason;
    const wrappedOverrides = {
        ...moduleOverrides,
        locateFile: (path, prefix) => {
            requestedFile = path;
            resolvedUrl = userLocateFile ? userLocateFile(path, prefix) : prefix + path;
            return resolvedUrl;
        },
        onAbort: (reason) => {
            abortReason = reason;
            if (userOnAbort) userOnAbort(reason);
        },
    };

    let Module;
    try {
        Module = await createRawModule(wrappedOverrides);
    } catch (cause) {
        throw new MeshioPlusPlusLoadError(
            `meshio++ (wasm): failed to instantiate the '${chosen}' variant (${glue}): ` +
                `${abortReason ?? cause.message ?? cause}. Emscripten requested ` +
                `'${requestedFile}' and locateFile returned '${resolvedUrl}'.`,
            { variant: chosen, glue, requestedFile, resolvedUrl, cause },
        );
    }

    // A mismatched locateFile (e.g. the seq .wasm handed to the mt glue) does
    // not always fail instantiation with a LinkError -- the two binaries share
    // enough of an export surface that it can link and then silently behave
    // like the wrong variant. parallelBackend() is the cheap, always-present
    // tell: catch it here rather than let every caller re-discover it.
    const expectedBackend = chosen === 'mt' ? 'openmp' : 'seq';
    const actualBackend = Module.parallelBackend();
    if (actualBackend !== expectedBackend) {
        throw new MeshioPlusPlusLoadError(
            `meshio++ (wasm): failed to instantiate the '${chosen}' variant (${glue}): ` +
                `loaded, but reports parallel backend '${actualBackend}' (expected ` +
                `'${expectedBackend}') -- locateFile likely returned the wrong .wasm binary. ` +
                `Emscripten requested '${requestedFile}' and locateFile returned '${resolvedUrl}'.`,
            { variant: chosen, glue, requestedFile, resolvedUrl },
        );
    }

    return {
        FS: Module.FS,
        readMesh: (path, format = '') => Module.readMesh(path, format),
        // Selective reads (see doc/selective_read.md). `arrays: null` reads
        // every data array, `arrays: []` reads none -- the distinction is
        // deliberate. Formats without a native selective path are read whole
        // and filtered, so the result is the same either way.
        // `timeStep` picks a step of a multi-step file: 0 (default) is the
        // first, negative counts from the end, out of range throws.
        // `lenient` downgrades "this reader cannot represent construct X" to a
        // warning plus a skip; a malformed file still throws.
        // `piece` keeps one partition/block of a partitioned file (VTKHDF): 0 is
        // the first, negative counts from the end; null (default) merges every
        // piece into one mesh with one cell region per piece.
        // `info: true` attaches the format's side channel as `mesh.info`
        // (openfoam/med/mdpa/ansysinp/unv/gmsh/exodus; ignored, not thrown,
        // for any other format) -- see doc/wasm.md's "Side channel (info)"
        // section. `pointsOnly`/`arrays` reach it only for the formats whose
        // info reader takes selective-read options (med/mdpa/gmsh/exodus).
        readMeshSelective: (
            path,
            {
                format = '',
                pointsOnly = false,
                arrays = null,
                timeStep = 0,
                lenient = false,
                piece = null,
                info = false,
            } = {},
        ) =>
            Module.readMeshSelective(
                path, format, pointsOnly, arrays, timeStep, lenient, piece, info,
            ),
        // Summarize a file without loading its heavy arrays. The returned
        // object's `fellBackToFullRead` says whether that was actually cheap.
        readMetadata: (path, format = '') => Module.readMetadata(path, format),
        readerSupportsOptions: (format) => Module.readerSupportsOptions(format),
        // `options`: `{encoding, codec, floatFormat, info}`, all optional --
        // unset/empty reproduces the exact pre-v11.2.0 write. `encoding` is
        // 'ascii'/'binary' (format-default otherwise); `codec` is a VTK-XML
        // (vtu/vtp) block-compression codec, 'none'/'zlib'/'lz4'/'zstd'; an
        // option a format cannot honour throws naming the format. `info`
        // writes that format's side channel (openfoam/mdpa/ansysinp/unv/gmsh/
        // med); when omitted, `mesh.info` is used instead if its own
        // `format` matches this write's -- a read(info:true) round-trips
        // back through a write with no extra plumbing. `info` given for a
        // format with no side-channel writer (e.g. exodus, read-only, or any
        // format without one at all) throws naming it. Returns every
        // virtual-FS path the write touched (new or changed), sorted -- more
        // than one for a multi-file writer (`.xdmf` + its `.h5` companion,
        // an OpenFOAM `polyMesh` directory's files, ...).
        writeMesh: (path, mesh, format = '', options = undefined) =>
            Module.writeMesh(path, mesh, format, options),
        // `options` adds `encoding`/`codec`/`floatFormat` to `inFormat`/
        // `outFormat` (see `writeMesh`). Returns the written paths, as
        // `writeMesh` does.
        convert: (
            inPath,
            outPath,
            { inFormat = '', outFormat = '', encoding, codec, floatFormat } = {},
        ) => Module.convert(inPath, inFormat, outPath, outFormat, { encoding, codec, floatFormat }),
        // Like `convert`, but writes a renderable *surface*: a volume mesh
        // becomes its boundary, everything else passes through, and the result
        // is linearized. Prefer this over readMesh -> extractSkin -> writeMesh
        // for anything headed to a renderer: it stays inside C++, so
        // multi-component data survives, which the flat JS mesh cannot carry.
        convertSurface: (inPath, outPath, { inFormat = '', outFormat = '' } = {}) =>
            Module.convertSurface(inPath, inFormat, outPath, outFormat),
        // Like `convertSurface`, but applies a pipeline of mesh operations
        // first -- entirely inside C++, so multi-component data survives them.
        // An empty pipeline is exactly `convertSurface`, which is what lets a
        // caller use one code path for both the plain and the post-operation
        // display, and what makes undo a replay rather than an inverse.
        convertSurfaceOps: (
            inPath,
            outPath,
            ops = [],
            { inFormat = '', outFormat = '', keepProvenance = false } = {}
        ) =>
            Module.convertSurfaceOps(inPath, inFormat, outPath, outFormat, ops, keepProvenance),
        // A whole settings.json pipeline (PascalCase vocabulary, see
        // doc/pipeline.md). Accepts the parsed object, the JSON text, or a
        // MEMFS path ending in ".json" -- the wasm binary carries no JSON
        // parser (JSON.parse is free here), so both string forms are resolved
        // to an object on this side of the boundary.
        runPipeline: (settings) => {
            let resolved = settings;
            if (typeof settings === 'string') {
                const text = settings.trimStart().startsWith('{')
                    ? settings
                    : new TextDecoder().decode(Module.FS.readFile(settings));
                resolved = JSON.parse(text);
            }
            return Module.runPipeline(resolved);
        },
        // Sequences: a set of MEMFS files (or the steps inside one multi-step
        // file) as one ordered transient dataset. See doc/sequences.md.
        // `source` is a glob pattern ('*' and '?' only) or an array of paths;
        // ordering is natural-numeric, so out_9.vtu precedes out_10.vtu.
        sequenceEntries: (source, options = undefined) =>
            Module.sequenceEntries(source, options),
        // Fan-in: N single-step files -> one multi-step file (XDMF today).
        // Streams -- one mesh alive at a time, whatever the step count.
        sequenceToTimeseries: (source, outPath, outFormat = '', options = undefined) =>
            Module.sequenceToTimeseries(source, outPath, outFormat, options),
        // Fan-out: one multi-step file -> one file per step. `outPattern` must
        // contain '{step}' or '{index}'; returns the MEMFS paths written.
        timeseriesToSequence: (inPath, outPattern, inFormat = '', outFormat = '') =>
            Module.timeseriesToSequence(inPath, inFormat, outPattern, outFormat),
        numNodesPerCell: () => Module.numNodesPerCell(),
        topologicalDimension: () => Module.topologicalDimension(),
        meshBackend: () => Module.meshBackend(),
        // "seq" for the sequential artifact, "openmp" for the threaded
        // meshioplusplus_wasm_mt one -- which of the two this instance loaded.
        parallelBackend: () => Module.parallelBackend(),
        hasCgnslib: () => Module.hasCgnslib(),
        // What this build can actually read/write, both sorted. Prefer this
        // over a hardcoded table: a few formats are read-only (openfoam) or
        // write-only (svg/tikz), and the HDF5/netCDF-backed ones are present
        // only in a build that linked them (the official artifact does).
        availableFormats: () => Module.availableFormats(),
        // Mesh operations (see doc/*.md per operation): computations ON a mesh,
        // not file formats. Index maps (crop/split/convertCells) are not carried
        // across the JS boundary -- use the record*Ids flags instead.
        extractSurface: (mesh, recordParentIds = false) =>
            Module.extractSurface(mesh, recordParentIds),
        extractSkin: (mesh, linearize = false) => Module.extractSkin(mesh, linearize),
        attachQuality: (mesh) => Module.attachQuality(mesh),
        sniffFormat: (path) => Module.sniffFormat(path),
        reorder: (mesh, method = 'rcm') => Module.reorder(mesh, method),
        computeBandwidth: (mesh) => Module.computeBandwidth(mesh),
        diff: (a, b, atol = 0, rtol = 0, unordered = false) =>
            Module.diff(a, b, atol, rtol, unordered),
        meshesEqual: (a, b, atol = 0, rtol = 0, unordered = false) =>
            Module.meshesEqual(a, b, atol, rtol, unordered),
        // `returnMaps` (default false): when true, returns
        // `{mesh, pointMaps, cellMaps}` instead of a bare mesh -- one array
        // per input mesh, in input order.
        merge: (
            meshes,
            weld = false,
            atol = 1e-12,
            sourceTag = true,
            dataPolicy = 'intersection',
            dropDuplicateCells = false,
            returnMaps = false,
        ) =>
            Module.merge(
                meshes, weld, atol, sourceTag, dataPolicy, dropDuplicateCells, returnMaps,
            ),
        transform: (mesh, matrix, rotateVectorData = false) =>
            Module.transform(mesh, matrix, rotateVectorData),
        // `returnMaps` (default false): when true, the result also carries
        // `pointMap`/`cellMaps` (input index -> output index, -1 if dropped).
        clean: (
            mesh,
            weld = false,
            atol = 1e-8,
            removeOrphans = true,
            dropDegenerate = true,
            dropDuplicateCells = true,
            returnMaps = false,
        ) =>
            Module.clean(
                mesh, weld, atol, removeOrphans, dropDegenerate, dropDuplicateCells, returnMaps,
            ),
        // `method` is 'taubin', 'laplacian' or 'odt' (tet-only). A negative
        // `lambda` means "this method's own default" (0.5 Laplacian, 0.33
        // Taubin) and is forwarded unchanged. `frozen` is an optional array of
        // 0-based point ids to pin outright, unioned with any boundary/feature
        // pins; an out-of-range id throws by name.
        smooth: (
            mesh,
            method = 'taubin',
            iterations = 10,
            lambda = -1,
            mu = -0.34,
            fixBoundary = true,
            preserveFeatures = true,
            featureAngle = 30,
            guardInversion = true,
            frozen = null,
        ) =>
            Module.smooth(
                mesh,
                method,
                iterations,
                lambda,
                mu,
                fixBoundary,
                preserveFeatures,
                featureAngle,
                guardInversion,
                frozen,
            ),
        // Cross-mesh field transfer: source point_data sampled at the target's
        // points, source cell_data by nearest source-cell centroid regardless
        // of the method. An empty `arrays` = every source point_data array.
        interpolate: (
            source,
            target,
            method = 'nearest',
            arrays = [],
            extrapolate = false,
            defaultValue = 0,
            onConflict = 'error',
        ) =>
            Module.interpolate(
                source,
                target,
                method,
                arrays,
                extrapolate,
                defaultValue,
                onConflict,
            ),
        // Mass-preserving cross-mesh field transfer: an exact overlap-measure
        // weighted remap (unlike interpolate's pointwise sampling). An empty
        // `arrays` = every source point_data AND cell_data array.
        conservativeInterpolate: (
            source,
            target,
            arrays = [],
            defaultValue = 0,
            onConflict = 'error',
        ) =>
            Module.conservativeInterpolate(
                source,
                target,
                arrays,
                defaultValue,
                onConflict,
            ),
        // Restore `fine`'s transitional (green) cells to their coarse parent,
        // read verbatim from `coarse` (a lookup, not a reconstruction).
        undoGreen: (coarse, fine) => Module.undoGreen(coarse, fine),
        // Each crop* returns a bare mesh, or `{mesh, pointMap, cellMaps}` when
        // `returnMaps` (the trailing argument, default false) is set.
        cropBbox: (mesh, lo, hi, mode = 'all', recordIds = false, returnMaps = false) =>
            Module.cropBbox(mesh, lo, hi, mode, recordIds, returnMaps),
        cropPlane: (mesh, point, normal, mode = 'all', recordIds = false, returnMaps = false) =>
            Module.cropPlane(mesh, point, normal, mode, recordIds, returnMaps),
        cropPredicate: (
            mesh, array, compare = '<', value = 0, recordIds = false, returnMaps = false,
        ) => Module.cropPredicate(mesh, array, compare, value, recordIds, returnMaps),
        slice: (mesh, origin, normal, recordParentIds = false) =>
            Module.slice(mesh, origin, normal, recordParentIds),
        grid: (dims, origin = null, spacing = null, maxCells = 20000000) =>
            Module.grid(dims, origin, spacing, maxCells),
        voxelize: (
            mesh,
            resolution = null,
            cellSize = 0,
            bounds = null,
            padding = 0,
            paddingRelative = 0,
            fill = 'all',
            sign = 'pseudonormal',
            attachOccupancy = false,
            maxCells = 20000000,
            watertightCheck = 'warn',
        ) =>
            Module.voxelize(mesh, resolution, cellSize, bounds, padding, paddingRelative,
                fill, sign, attachOccupancy, maxCells, watertightCheck),
        surfaceWatertightCheck: (mesh) => Module.surfaceWatertightCheck(mesh),
        sampleDistance: (surface, points, sign = 'pseudonormal', band = 0, watertightCheck = 'warn') =>
            Module.sampleDistance(surface, points, sign, band, watertightCheck),
        distanceToSurface: (
            query,
            surface,
            sign = 'pseudonormal',
            location = 'corner',
            band = 0,
            recordInside = false,
            watertightCheck = 'warn',
        ) =>
            Module.distanceToSurface(query, surface, sign, location, band, recordInside,
                watertightCheck),
        computeSdf: (
            surface,
            structure = 'voxel',
            resolution = null,
            cellSize = 0,
            bounds = null,
            padding = 0,
            paddingRelative = 0.1,
            rootResolution = 8,
            maxDepth = 4,
            bandCells = 1,
            recordLevels = true,
            maxCells = 20000000,
            sign = 'pseudonormal',
            location = 'corner',
            band = 0,
            watertightCheck = 'warn',
        ) =>
            Module.computeSdf(surface, structure, resolution, cellSize, bounds, padding,
                paddingRelative, rootResolution, maxDepth, bandCells, recordLevels, maxCells,
                sign, location, band, watertightCheck),
        isosurface: (mesh, array, isovalues, component = -1, recordParentIds = false) =>
            Module.isosurface(
                mesh,
                array,
                Array.isArray(isovalues) ? isovalues : [isovalues],
                component,
                recordParentIds,
            ),
        gradient: (
            mesh,
            array,
            operator = 'gradient',
            method = 'green-gauss',
            location = 'cell',
            output = '',
            component = -1,
            overwrite = false,
        ) =>
            Module.gradient(mesh, array, operator, method, location, output, component, overwrite),
        hessian: (
            mesh,
            array,
            method = 'green-gauss',
            location = 'cell',
            output = '',
            overwrite = false,
        ) => Module.hessian(mesh, array, method, location, output, overwrite),
        estimateError: (
            mesh,
            array,
            method = 'zz',
            marking = 'none',
            markingValue = 0.0,
            output = '',
            marked = '',
            overwrite = false,
        ) =>
            Module.estimateError(
                mesh,
                array,
                method,
                marking,
                markingValue,
                output,
                marked,
                overwrite,
            ),
        remesh: (
            mesh,
            numClusters,
            subdivide = -1,
            subsampleRatio = 10.0,
            maxSubdivide = 4,
            maxIterations = 100,
            maxRepairPasses = 10,
            metric = 'isotropic',
            gradation = 0.0,
            preserveBoundary = true,
            maxAnisotropy = 4.0,
        ) =>
            Module.remesh(
                mesh,
                numClusters,
                subdivide,
                subsampleRatio,
                maxSubdivide,
                maxIterations,
                maxRepairPasses,
                metric,
                gradation,
                preserveBoundary,
                maxAnisotropy,
            ),
        remeshVolume: (
            mesh,
            resolution = null,
            cellSize = 0,
            bounds = null,
            padding = 0,
            paddingRelative = 0.1,
            maxCells = 20000000,
            maxTets = 20000000,
            warpFraction = 0.35,
            sign = 'pseudonormal',
            watertightCheck = 'warn',
        ) =>
            Module.remeshVolume(mesh, resolution, cellSize, bounds, padding, paddingRelative,
                maxCells, maxTets, warpFraction, sign, watertightCheck),
        optimizeVolume: (
            mesh,
            maxIterations = 10,
            relocate = true,
            flip = true,
            preserveBoundary = true,
            minImprovement = 1e-6,
        ) =>
            Module.optimizeVolume(mesh, maxIterations, relocate, flip, preserveBoundary,
                minImprovement),
        computeCurvature: (
            mesh,
            mean = true,
            gaussian = true,
            dualArea = 'mixed-voronoi',
            includeBoundary = false,
            recordArea = false,
            recordPrincipal = false,
            region = '',
        ) =>
            Module.computeCurvature(mesh, mean, gaussian, dualArea, includeBoundary,
                recordArea, recordPrincipal, region),
        repair: (
            mesh,
            fixOrientation = true,
            orientOutward = true,
            fillHoles = true,
            splitNonManifold = true,
            maxHoleEdges = 10,
            weldTolerance = 0,
            recordProvenance = false,
        ) =>
            Module.repair(mesh, fixOrientation, orientOutward, fillHoles, splitNonManifold,
                maxHoleEdges, weldTolerance, recordProvenance),
        shrinkwrap: (
            mesh,
            target,
            offset = 0,
            maxDistance = 0,
            weights = '',
            targetRegion = '',
            normalWeight = 'angle',
            recordDistance = false,
            recordClosestCell = false,
        ) =>
            Module.shrinkwrap(mesh, target, offset, maxDistance, weights, targetRegion,
                normalWeight, recordDistance, recordClosestCell),
        sobolevDeform: (
            mesh,
            array,
            lengthScale,
            fixedPointsArray = '',
            fixBoundary = false,
            recordFiltered = false,
            maxIterations = 128,
            tolerance = 1e-10,
        ) =>
            Module.sobolevDeform(mesh, array, lengthScale, fixedPointsArray, fixBoundary,
                recordFiltered, maxIterations, tolerance),
        // `returnMaps` (default false): when true, each `{key, mesh}` piece
        // also carries `pointMap`/`cellMaps`.
        split: (mesh, by, tagName = '', returnMaps = false) =>
            Module.split(mesh, by, tagName, returnMaps),
        // `returnMaps` (default false): when true, returns
        // `{mesh, pointMap, cellMaps}` instead of a bare mesh.
        convertCells: (mesh, mode = 'linearize', recordParentIds = false, returnMaps = false) =>
            Module.convertCells(mesh, mode, recordParentIds, returnMaps),
        // `returnMaps` (default false): when true, returns `{mesh, cellMaps}`
        // instead of a bare mesh -- there is no point map (subdivide never
        // prunes or renumbers a point).
        subdivide: (mesh, recordParentIds = false, returnMaps = false) =>
            Module.subdivide(mesh, recordParentIds, returnMaps),
        // `returnMaps` (default false): when true, returns `{mesh, cellMap}`
        // instead of a bare mesh -- a single FLAT array (global cell index ->
        // global cell index), unlike the other ops' per-block `cellMaps`.
        agglomerate: (mesh, targetGroupSize = 8, returnMaps = false) =>
            Module.agglomerate(mesh, targetGroupSize, returnMaps),
        // `returnMaps` (default false): when true, returns
        // `{mesh, pointMap, cellMaps}` instead of a bare mesh.
        refine: (mesh, levels = 1, recordParentIds = false, options = undefined,
            returnMaps = false) =>
            Module.refine(mesh, levels, recordParentIds, options, returnMaps),
        // Exactly one of ratio / targetFaces / maxError must be non-negative.
        // `frozen` is an optional array of 0-based point ids to pin outright;
        // an out-of-range id throws by name. `returnMaps` (default false):
        // when true, the result also carries `pointMap`/`cellMaps`.
        decimate: (
            mesh,
            ratio = -1,
            targetFaces = -1,
            maxError = -1,
            placement = 'optimal',
            preserveBoundary = true,
            preserveFeatures = true,
            featureAngle = 30,
            frozen = null,
            returnMaps = false,
        ) =>
            Module.decimate(
                mesh,
                ratio,
                targetFaces,
                maxError,
                placement,
                preserveBoundary,
                preserveFeatures,
                featureAngle,
                frozen,
                returnMaps,
            ),
        // Tetrahedral VOLUME decimation (decimate's tet-edge-collapse sibling).
        // Exactly one of ratio / targetCells / maxError must be non-negative.
        // `preserveBoundary` defaults to false here, matching the C++ default
        // (decimate's own default is true) -- decimateVolume's boundary is
        // usually interior geometry a solver still wants simplified.
        // `returnMaps` (default false): when true, the result also carries
        // `pointMap`/`cellMaps`.
        decimateVolume: (
            mesh,
            ratio = -1,
            targetCells = -1,
            maxError = -1,
            placement = 'optimal',
            preserveBoundary = false,
            preserveFeatures = true,
            featureAngle = 30,
            frozen = null,
            returnMaps = false,
        ) =>
            Module.decimateVolume(
                mesh,
                ratio,
                targetCells,
                maxError,
                placement,
                preserveBoundary,
                preserveFeatures,
                featureAngle,
                frozen,
                returnMaps,
            ),
        // `returnMaps` (default false): when true, each `{partId, mesh}`
        // piece also carries `pointMap`/`cellMaps`.
        partition: (
            mesh,
            nparts,
            method = 'auto',
            imbalance = 0.03,
            mode = 'eco',
            seed = 0,
            recordIds = false,
            ghostLayers = 0,
            weightsKey = '',
            returnMaps = false,
        ) =>
            Module.partition(
                mesh,
                nparts,
                method,
                imbalance,
                mode,
                seed,
                recordIds,
                ghostLayers,
                weightsKey,
                returnMaps,
            ),
        partitionLabels: (
            mesh,
            nparts,
            method = 'auto',
            imbalance = 0.03,
            mode = 'eco',
            seed = 0,
            weightsKey = '',
        ) => Module.partitionLabels(mesh, nparts, method, imbalance, mode, seed, weightsKey),
        stats: (mesh) => Module.stats(mesh),

        // Provenance (see doc/provenance.md). The C++ scope is RAII, but two
        // separate JS calls cannot be, so `withProvenance` pairs them in a
        // try/finally -- a throw inside the body must not strand the scope.
        // The raw begin/end are exposed too for a caller whose control flow
        // does not fit a callback.
        withProvenance: (mode, fn) => {
            Module.provenanceBegin(mode ?? 1);
            try {
                return fn();
            } finally {
                Module.provenanceEnd();
            }
        },
        provenanceBegin: (mode) => Module.provenanceBegin(mode ?? 1),
        provenanceEnd: () => Module.provenanceEnd(),
        provenanceNote: (category, detail) => Module.provenanceNote(category, detail),
        provenanceSetSource: (path, format) => Module.provenanceSetSource(path, format),
        provenanceSetTarget: (format, encoding, codec, floatFormat) =>
            Module.provenanceSetTarget(format, encoding ?? '', codec ?? '', floatFormat ?? ''),
        readProvenance: (path) => Module.readProvenance(path),
        // Data operations (see doc/data_operations.md): act on point_data /
        // cell_data / field_data only -- the geometry is never modified.
        dataDrop: (mesh, location, names = [], ignoreMissing = false) =>
            Module.dataDrop(mesh, location, names, ignoreMissing),
        dataKeep: (mesh, location, names = [], ignoreMissing = false) =>
            Module.dataKeep(mesh, location, names, ignoreMissing),
        dataRename: (mesh, location, from, to) => Module.dataRename(mesh, location, from, to),
        dataPointToCell: (mesh, names = [], suffix = '') =>
            Module.dataPointToCell(mesh, names, suffix),
        dataCellToPoint: (mesh, names = [], weight = 'uniform', suffix = '') =>
            Module.dataCellToPoint(mesh, names, weight, suffix),
        dataCalc: (mesh, expression, location, outputName, overwrite = false) =>
            Module.dataCalc(mesh, expression, location, outputName, overwrite),
        dataCondition: (
            mesh,
            location,
            names = [],
            mode = 'clamp',
            lo = 0,
            hi = 1,
            scope = 'component',
            nanPolicy = 'ignore',
            nanReplacement = 0,
            suffix = '',
        ) =>
            Module.dataCondition(
                mesh, location, names, mode, lo, hi, scope, nanPolicy, nanReplacement, suffix,
            ),
        dataInfo: (mesh) => Module.dataInfo(mesh),
        dataIntegrate: (mesh, arrays = []) => Module.dataIntegrate(mesh, arrays),
        // Transient (time-series) XDMF -- the one *stateful* thing in this API.
        // The raw binding is an opaque integer handle plus seven free
        // functions (see bindings/wasm/js_bindings.cpp for why it is not an
        // embind class_); this wrapper is the ergonomic face of it, so callers
        // never see the handle and never call an Emscripten `.delete()`.
        //
        // The `.xdmf` appears at close()/finalize(), or earlier at a flush() --
        // the collection element has to enclose every step -- and with
        // dataFormat 'HDF' the series is TWO files in the virtual FS: `<path>`
        // and its sibling `<path minus extension>.h5`. Copy BOTH out of
        // Module.FS. `mode: 'append'` continues a series already at `path`.
        createXdmfTimeSeriesWriter: (
            path,
            { dataFormat = 'HDF', gzipLevel = -1, mode = 'truncate', autoFlush = false } = {},
        ) => {
            const handle = Module.xdmfSeriesCreate(path, dataFormat, gzipLevel, mode, autoFlush);
            let open = true;
            return {
                writePointsCells: (mesh) => Module.xdmfSeriesWritePointsCells(handle, mesh),
                writeData: (time, mesh) => Module.xdmfSeriesWriteData(handle, time, mesh),
                // Raw solver arrays instead of a mesh; `components` gives the
                // per-entity width of any array that is not a scalar.
                writeDataArrays: (time, pointData, cellData = {}, components = {}) =>
                    Module.xdmfSeriesWriteDataArrays(
                        handle,
                        time,
                        widenBigIntArrays(pointData),
                        widenBigIntArrays(cellData),
                        components,
                    ),
                // Make the `.xdmf` readable now, without finalizing.
                flush: () => Module.xdmfSeriesFlush(handle),
                finalize: () => Module.xdmfSeriesFinalize(handle),
                numSteps: () => Module.xdmfSeriesNumSteps(handle),
                finalized: () => Module.xdmfSeriesFinalized(handle),
                // Safe to call twice; safe to call in a `finally`. Finalizes
                // explicitly first so a write failure is thrown rather than
                // swallowed by the C++ destructor (which must not throw).
                close: () => {
                    if (!open) return;
                    open = false;
                    try {
                        Module.xdmfSeriesFinalize(handle);
                    } finally {
                        Module.xdmfSeriesFree(handle);
                    }
                },
            };
        },
        // Stateful sequence reader (see doc/sequences.md) -- the other
        // stateful thing in this API, the same opaque-handle-plus-free-
        // functions shape as createXdmfTimeSeriesWriter above. `source`/
        // `options` are exactly sequenceEntries'; this plans the sequence
        // once (`entries()`) and lets a caller read one step at a time
        // (`read()`) without holding more than one mesh alive, unlike
        // sequenceEntries + readMesh in a loop, which still requires the
        // caller to resolve the format/step itself.
        openSequence: (source, options = undefined) => {
            const handle = Module.sequenceOpen(source, options);
            const count = Module.sequenceCount(handle);
            const entry = (i) => ({
                path: Module.sequencePath(handle, i),
                step: Module.sequenceStep(handle, i),
                time: Module.sequenceTime(handle, i),
                timeSource: Module.sequenceTimeSource(handle, i),
            });
            let open = true;
            return {
                count,
                path: (i) => Module.sequencePath(handle, i),
                step: (i) => Module.sequenceStep(handle, i),
                time: (i) => Module.sequenceTime(handle, i),
                timeSource: (i) => Module.sequenceTimeSource(handle, i),
                entry,
                entries: () => Array.from({ length: count }, (_, i) => entry(i)),
                read: (i, { pointsOnly = false, arrays = null, lenient = false } = {}) =>
                    Module.sequenceRead(handle, i, { pointsOnly, arrays, lenient }),
                // Safe to call twice; safe to call in a `finally`.
                close: () => {
                    if (!open) return;
                    open = false;
                    Module.sequenceFree(handle);
                },
            };
        },
    };
}

export default loadMeshioPlusPlus;
