// Ergonomic wrapper around the raw Emscripten/embind glue generated by
// bindings/wasm/js_bindings.cpp (see ../../../CMakeLists.txt's `if(EMSCRIPTEN)`
// block and ../../../build/configure-wasm.sh). The raw glue (dist/
// meshioplusplus_wasm.mjs, built by CMake, not hand-written) exports a
// MODULARIZE=1 + EXPORT_ES6=1 factory function; this file wraps that
// factory so callers get:
//   - default parameters (`format = ''` to infer from the file extension,
//     matching the C++ side's `resolve_format`, instead of Emscripten's raw
//     embind functions which require every parameter explicitly);
//   - a `convert()` with a friendlier `{ inFormat, outFormat }` options bag
//     instead of two trailing positional strings;
//   - `Module.FS` passed through unwrapped, since virtual-filesystem access
//     is the one place this package intentionally stays close to the raw
//     Emscripten API (see the README's "Reading/writing files" section).
//
// Each call to loadMeshioPlusPlus() instantiates a fresh, independent WASM
// module instance (safe to call more than once, e.g. one per Web Worker).
//
// The package ships TWO native artifacts and picks one at load time:
//   - meshioplusplus_wasm      the sequential build (always loadable);
//   - meshioplusplus_wasm_mt   the threaded build (OpenMP over Wasm threads =
//                              pthreads/SharedArrayBuffer), which is faster for
//                              the mesh operations but only loads where the page
//                              is *cross-origin isolated* (COOP `same-origin` +
//                              COEP `require-corp`); it aborts on instantiation
//                              otherwise, with no in-artifact fallback.
// resolveVariant() below chooses: the threaded build under Node (where
// SharedArrayBuffer is always available) and in a cross-origin-isolated browser
// context, else the sequential one. The dynamic import()s are literal so
// bundlers (Vite) emit both chunks. Callers can force a build with the
// `{ variant }` option.

/**
 * Decide which native artifact to load.
 * @param {'auto'|'mt'|'seq'} variant
 * @returns {'mt'|'seq'}
 */
function resolveVariant(variant) {
    if (variant === 'mt' || variant === 'seq') return variant;
    // `crossOriginIsolated` is a browser global; it is `undefined` under Node,
    // where Wasm threads (worker_threads + SharedArrayBuffer) always work.
    if (typeof crossOriginIsolated === 'undefined') return 'mt';
    return crossOriginIsolated ? 'mt' : 'seq';
}

/**
 * A rectangular (uniform node count) group of cells.
 * @typedef {Object} RectangularCellBlock
 * @property {string} type - meshio++ cell type name (e.g. "triangle", "tetra10").
 * @property {Int32Array} data - flat, row-major connectivity (numCells * nodesPerCell).
 * @property {number} nodesPerCell
 */

/**
 * A 1-level ragged (jagged polygon) block: rows of varying node count, so
 * there is no single `nodesPerCell`. Two flat CSR arrays instead of a nested
 * array of arrays, which embind has no efficient representation for.
 * @typedef {Object} PolygonCellBlock
 * @property {string} type
 * @property {Int32Array} data - every row's node ids concatenated.
 * @property {Int32Array} rowOffsets - each cell's start in `data` (numCells + 1).
 */

/**
 * A 2-level ragged (polyhedron) block: each cell a list of faces, each face a
 * list of node ids.
 * @typedef {Object} PolyhedronCellBlock
 * @property {string} type
 * @property {Int32Array} data - every face's node ids concatenated.
 * @property {Int32Array} faceOffsets - each face's start in `data` (totalFaces + 1).
 * @property {Int32Array} cellOffsets - each cell's start in the face list (numCells + 1).
 */

/**
 * One homogeneous group of cells. Which shape it is is told by key presence:
 * `cellOffsets` means polyhedron, `rowOffsets` means polygon, `nodesPerCell`
 * means rectangular. See doc/polyhedra.md.
 * @typedef {RectangularCellBlock | PolygonCellBlock | PolyhedronCellBlock} CellBlock
 */

/**
 * @typedef {Object} XdmfTimeSeriesWriter
 * @property {(mesh: Mesh) => void} writePointsCells - the static grid, once.
 * @property {(time: number, mesh: Mesh) => void} writeData - one step's data.
 * @property {(time: number, pointData: Object<string, Float64Array>, cellData?: Object<string, Float64Array>, components?: Object<string, number>) => void} writeDataArrays - one step from raw arrays.
 * @property {() => void} flush - write the `.xdmf` as it stands, without finalizing.
 * @property {() => void} finalize - write the `.xdmf`; idempotent.
 * @property {() => number} numSteps
 * @property {() => boolean} finalized
 * @property {() => void} close - finalize (if needed) and release the handle.
 */

/**
 * @typedef {Object} Mesh
 * @property {Float64Array} points - flat, row-major (numPoints * dim).
 * @property {number} dim - 2 or 3.
 * @property {CellBlock[]} cells
 * @property {Object<string, Float64Array>} [point_data]
 * @property {Object<string, number>} [point_data_components] - per-entity width of any non-scalar point_data array, since a flat typed array carries no shape; absent name = 1 component.
 * @property {Object<string, Float64Array[]>} [cell_data] - one array per cell block, same order as `cells`.
 * @property {Object<string, number>} [cell_data_components] - per-entity width of any non-scalar cell_data array (one value per array, not per block).
 * @property {Object<string, Float64Array>} [field_data]
 * @property {Object<string, number>} [field_data_components] - per-entity width of any non-scalar field_data array.
 */

/**
 * Instantiate a fresh meshio++ WASM module.
 *
 * @param {object} [moduleOverrides] - forwarded to the Emscripten module
 *   factory as-is (e.g. `{ locateFile: (p) => new URL(p, import.meta.url) }`
 *   if you need to relocate the `.wasm` binary for a bundler/CDN setup).
 *   `locateFile` receives the requested filename, so return the URL matching
 *   the loaded variant (`meshioplusplus_wasm.wasm` or `_wasm_mt.wasm`).
 * @param {object} [options]
 * @param {'auto'|'mt'|'seq'} [options.variant='auto'] - which native artifact to
 *   load. `auto` picks the threaded (`mt`) build under Node and in a
 *   cross-origin-isolated browser, else the sequential (`seq`) build; `mt`/`seq`
 *   force one (`mt` aborts if the environment cannot host Wasm threads).
 * @returns {Promise<{
 *   FS: object,
 *   readMesh: (path: string, format?: string) => Mesh,
 *   readMeshSelective: (path: string, options?: {format?: string, pointsOnly?: boolean, arrays?: string[], timeStep?: number, lenient?: boolean}) => Mesh,
 *   readMetadata: (path: string, format?: string) => object,
 *   readerSupportsOptions: (format: string) => boolean,
 *   writeMesh: (path: string, mesh: Mesh, format?: string) => void,
 *   convert: (inPath: string, outPath: string, options?: {inFormat?: string, outFormat?: string}) => void,
 *   convertSurface: (inPath: string, outPath: string, options?: {inFormat?: string, outFormat?: string}) => void,
 *   convertSurfaceOps: (inPath: string, outPath: string, ops?: object[], options?: {inFormat?: string, outFormat?: string, keepProvenance?: boolean}) => {steps: object[], warnings: string[]},
 *   runPipeline: (settings: object|string) => {steps: object[], warnings: string[]},
 *   sequenceEntries: (source: string|string[], options?: object) => object[],
 *   sequenceToTimeseries: (source: string|string[], outPath: string, outFormat?: string, options?: object) => number,
 *   timeseriesToSequence: (inPath: string, outPattern: string, inFormat?: string, outFormat?: string) => string[],
 *   numNodesPerCell: () => Object<string, number>,
 *   topologicalDimension: () => Object<string, number>,
 *   meshBackend: () => string,
 *   parallelBackend: () => string,
 *   hasCgnslib: () => boolean,
 *   availableFormats: () => {readers: string[], writers: string[]},
 *   extractSurface: (mesh: Mesh, recordParentIds?: boolean) => Mesh,
 *   extractSkin: (mesh: Mesh, linearize?: boolean) => Mesh,
 *   attachQuality: (mesh: Mesh) => Mesh,
 *   sniffFormat: (path: string) => string,
 *   reorder: (mesh: Mesh, method?: string) => object,
 *   computeBandwidth: (mesh: Mesh) => number,
 *   diff: (a: Mesh, b: Mesh, atol?: number, rtol?: number, unordered?: boolean) => object,
 *   meshesEqual: (a: Mesh, b: Mesh, atol?: number, rtol?: number, unordered?: boolean) => boolean,
 *   merge: (meshes: Mesh[], weld?: boolean, atol?: number, sourceTag?: boolean, dataPolicy?: string, dropDuplicateCells?: boolean) => Mesh,
 *   transform: (mesh: Mesh, matrix: number[], rotateVectorData?: boolean) => Mesh,
 *   clean: (mesh: Mesh, weld?: boolean, atol?: number, removeOrphans?: boolean, dropDegenerate?: boolean, dropDuplicateCells?: boolean) => {mesh: Mesh, pointsWelded: number, pointsRemovedOrphan: number, cellsDroppedDegenerate: number, cellsDroppedDuplicate: number},
 *   smooth: (mesh: Mesh, method?: string, iterations?: number, lambda?: number, mu?: number, fixBoundary?: boolean, preserveFeatures?: boolean, featureAngle?: number, guardInversion?: boolean) => {mesh: Mesh, numNodesMoved: number, maxDisplacement: number, numSkippedInversion: number},
 *   cropBbox: (mesh: Mesh, lo: number[], hi: number[], mode?: string, recordIds?: boolean) => Mesh,
 *   cropPlane: (mesh: Mesh, point: number[], normal: number[], mode?: string, recordIds?: boolean) => Mesh,
 *   cropPredicate: (mesh: Mesh, array: string, compare?: string, value?: number, recordIds?: boolean) => Mesh,
 *   slice: (mesh: Mesh, origin: number[], normal: number[], recordParentIds?: boolean) => Mesh,
 *   isosurface: (mesh: Mesh, array: string, isovalues: number|number[], component?: number, recordParentIds?: boolean) => Mesh,
 *   grid: (dims: number[], origin?: number[], spacing?: number[], maxCells?: number) => Mesh,
 *   voxelize: (mesh: Mesh, resolution?: number[], cellSize?: number, bounds?: number[], padding?: number, paddingRelative?: number, fill?: string, sign?: string, attachOccupancy?: boolean, maxCells?: number, watertightCheck?: string) => {mesh: Mesh, dims: number[], origin: number[], spacing: number[], numOccupied: number},
 *   surfaceWatertightCheck: (mesh: Mesh) => {boundaryEdges: number, nonManifoldEdges: number, inconsistentPairs: number, degenerateTriangles: number, watertight: boolean},
 *   sampleDistance: (surface: Mesh, points: number[], sign?: string, band?: number, watertightCheck?: string) => Float64Array,
 *   distanceToSurface: (query: Mesh, surface: Mesh, sign?: string, location?: string, band?: number, recordInside?: boolean, watertightCheck?: string) => {mesh: Mesh, numBanded: number, quality: object},
 *   computeSdf: (surface: Mesh, structure?: string, resolution?: number[], cellSize?: number, bounds?: number[], padding?: number, paddingRelative?: number, rootResolution?: number, maxDepth?: number, bandCells?: number, recordLevels?: boolean, maxCells?: number, sign?: string, location?: string, band?: number, watertightCheck?: string) => {mesh: Mesh, dims: number[], origin: number[], spacing: number[], maxDepth: number, numBanded: number, quality: object},
 *   gradient: (mesh: Mesh, array: string, operator?: string, method?: string, location?: string, output?: string, component?: number, overwrite?: boolean) => {mesh: Mesh, numSkipped: number, numFallback: number},
 *   hessian: (mesh: Mesh, array: string, method?: string, location?: string, output?: string, overwrite?: boolean) => {mesh: Mesh, numSkipped: number, numFallback: number},
 *   estimateError: (mesh: Mesh, array: string, method?: string, marking?: string, markingValue?: number, output?: string, marked?: string, overwrite?: boolean) => {mesh: Mesh, globalError: number, numSkipped: number, numMarked: number},
 *   remesh: (mesh: Mesh, numClusters: number, subdivide?: number, subsampleRatio?: number, maxSubdivide?: number, maxIterations?: number, maxRepairPasses?: number, metric?: string) => {mesh: Mesh, numClusters: number, numIterations: number, subdivideApplied: number, numIsolatedClusters: number},
 *   split: (mesh: Mesh, by: string, tagName?: string) => {key: string, mesh: Mesh}[],
 *   convertCells: (mesh: Mesh, mode?: string, recordParentIds?: boolean) => Mesh,
 *   subdivide: (mesh: Mesh, recordParentIds?: boolean) => Mesh,
 *   agglomerate: (mesh: Mesh, targetGroupSize?: number) => Mesh,
 *   refine: (mesh: Mesh, levels?: number, recordParentIds?: boolean,
 *            options?: object) => Mesh,
 *   decimate: (mesh: Mesh, ratio?: number, targetFaces?: number, maxError?: number, placement?: string, preserveBoundary?: boolean, preserveFeatures?: boolean, featureAngle?: number) => {mesh: Mesh, facesRemoved: number, pointsRemoved: number, collapsesRejected: number, maxErrorApplied: number},
 *   stats: (mesh: Mesh) => object,
 *   dataDrop: (mesh: Mesh, location: string, names?: string[], ignoreMissing?: boolean) => Mesh,
 *   dataKeep: (mesh: Mesh, location: string, names?: string[], ignoreMissing?: boolean) => Mesh,
 *   dataRename: (mesh: Mesh, location: string, from: string, to: string) => Mesh,
 *   dataPointToCell: (mesh: Mesh, names?: string[], suffix?: string) => Mesh,
 *   dataCellToPoint: (mesh: Mesh, names?: string[], weight?: string, suffix?: string) => Mesh,
 *   dataCalc: (mesh: Mesh, expression: string, location: string, outputName: string, overwrite?: boolean) => Mesh,
 *   dataCondition: (mesh: Mesh, location: string, names?: string[], mode?: string, lo?: number, hi?: number, scope?: string, nanPolicy?: string, nanReplacement?: number, suffix?: string) => Mesh,
 *   dataInfo: (mesh: Mesh) => object[],
 *   dataIntegrate: (mesh: Mesh, arrays?: string[]) => object[],
 *   createXdmfTimeSeriesWriter: (path: string, options?: {dataFormat?: string, gzipLevel?: number, mode?: 'truncate'|'append', autoFlush?: boolean}) => XdmfTimeSeriesWriter,
 * }>}
 */
export async function loadMeshioPlusPlus(moduleOverrides = {}, { variant = 'auto' } = {}) {
    const chosen = resolveVariant(variant);
    // Literal specifiers so bundlers emit both chunks; the sequential one is
    // the fallback whenever threads are unavailable.
    const { default: createRawModule } =
        chosen === 'mt'
            ? await import('../dist/meshioplusplus_wasm_mt.mjs')
            : await import('../dist/meshioplusplus_wasm.mjs');
    const Module = await createRawModule(moduleOverrides);
    return {
        FS: Module.FS,
        readMesh: (path, format = '') => Module.readMesh(path, format),
        // Selective reads (see doc/selective_read.md). `arrays: null` reads
        // every data array, `arrays: []` reads none -- the distinction is
        // deliberate. Formats without a native selective path are read whole
        // and filtered, so the result is the same either way.
        // `timeStep` picks a step of a multi-step file: 0 (default) is the
        // first, negative counts from the end, out of range throws.
        // `lenient` downgrades "this reader cannot represent construct X" to a
        // warning plus a skip; a malformed file still throws.
        readMeshSelective: (
            path,
            {
                format = '',
                pointsOnly = false,
                arrays = null,
                timeStep = 0,
                lenient = false,
            } = {},
        ) => Module.readMeshSelective(path, format, pointsOnly, arrays, timeStep, lenient),
        // Summarize a file without loading its heavy arrays. The returned
        // object's `fellBackToFullRead` says whether that was actually cheap.
        readMetadata: (path, format = '') => Module.readMetadata(path, format),
        readerSupportsOptions: (format) => Module.readerSupportsOptions(format),
        writeMesh: (path, mesh, format = '') => Module.writeMesh(path, mesh, format),
        convert: (inPath, outPath, { inFormat = '', outFormat = '' } = {}) =>
            Module.convert(inPath, inFormat, outPath, outFormat),
        // Like `convert`, but writes a renderable *surface*: a volume mesh
        // becomes its boundary, everything else passes through, and the result
        // is linearized. Prefer this over readMesh -> extractSkin -> writeMesh
        // for anything headed to a renderer: it stays inside C++, so
        // multi-component data survives, which the flat JS mesh cannot carry.
        convertSurface: (inPath, outPath, { inFormat = '', outFormat = '' } = {}) =>
            Module.convertSurface(inPath, inFormat, outPath, outFormat),
        // Like `convertSurface`, but applies a pipeline of mesh operations
        // first -- entirely inside C++, so multi-component data survives them.
        // An empty pipeline is exactly `convertSurface`, which is what lets a
        // caller use one code path for both the plain and the post-operation
        // display, and what makes undo a replay rather than an inverse.
        convertSurfaceOps: (
            inPath,
            outPath,
            ops = [],
            { inFormat = '', outFormat = '', keepProvenance = false } = {}
        ) =>
            Module.convertSurfaceOps(inPath, inFormat, outPath, outFormat, ops, keepProvenance),
        // A whole settings.json pipeline (PascalCase vocabulary, see
        // doc/pipeline.md). Accepts the parsed object, the JSON text, or a
        // MEMFS path ending in ".json" -- the wasm binary carries no JSON
        // parser (JSON.parse is free here), so both string forms are resolved
        // to an object on this side of the boundary.
        runPipeline: (settings) => {
            let resolved = settings;
            if (typeof settings === 'string') {
                const text = settings.trimStart().startsWith('{')
                    ? settings
                    : new TextDecoder().decode(Module.FS.readFile(settings));
                resolved = JSON.parse(text);
            }
            return Module.runPipeline(resolved);
        },
        // Sequences: a set of MEMFS files (or the steps inside one multi-step
        // file) as one ordered transient dataset. See doc/sequences.md.
        // `source` is a glob pattern ('*' and '?' only) or an array of paths;
        // ordering is natural-numeric, so out_9.vtu precedes out_10.vtu.
        sequenceEntries: (source, options = undefined) =>
            Module.sequenceEntries(source, options),
        // Fan-in: N single-step files -> one multi-step file (XDMF today).
        // Streams -- one mesh alive at a time, whatever the step count.
        sequenceToTimeseries: (source, outPath, outFormat = '', options = undefined) =>
            Module.sequenceToTimeseries(source, outPath, outFormat, options),
        // Fan-out: one multi-step file -> one file per step. `outPattern` must
        // contain '{step}' or '{index}'; returns the MEMFS paths written.
        timeseriesToSequence: (inPath, outPattern, inFormat = '', outFormat = '') =>
            Module.timeseriesToSequence(inPath, inFormat, outPattern, outFormat),
        numNodesPerCell: () => Module.numNodesPerCell(),
        topologicalDimension: () => Module.topologicalDimension(),
        meshBackend: () => Module.meshBackend(),
        // "seq" for the sequential artifact, "openmp" for the threaded
        // meshioplusplus_wasm_mt one -- which of the two this instance loaded.
        parallelBackend: () => Module.parallelBackend(),
        hasCgnslib: () => Module.hasCgnslib(),
        // What this build can actually read/write, both sorted. Prefer this
        // over a hardcoded table: a few formats are read-only (openfoam) or
        // write-only (svg/tikz), and the HDF5/netCDF-backed ones are present
        // only in a build that linked them (the official artifact does).
        availableFormats: () => Module.availableFormats(),
        // Mesh operations (see doc/*.md per operation): computations ON a mesh,
        // not file formats. Index maps (crop/split/convertCells) are not carried
        // across the JS boundary -- use the record*Ids flags instead.
        extractSurface: (mesh, recordParentIds = false) =>
            Module.extractSurface(mesh, recordParentIds),
        extractSkin: (mesh, linearize = false) => Module.extractSkin(mesh, linearize),
        attachQuality: (mesh) => Module.attachQuality(mesh),
        sniffFormat: (path) => Module.sniffFormat(path),
        reorder: (mesh, method = 'rcm') => Module.reorder(mesh, method),
        computeBandwidth: (mesh) => Module.computeBandwidth(mesh),
        diff: (a, b, atol = 0, rtol = 0, unordered = false) =>
            Module.diff(a, b, atol, rtol, unordered),
        meshesEqual: (a, b, atol = 0, rtol = 0, unordered = false) =>
            Module.meshesEqual(a, b, atol, rtol, unordered),
        merge: (
            meshes,
            weld = false,
            atol = 1e-12,
            sourceTag = true,
            dataPolicy = 'intersection',
            dropDuplicateCells = false,
        ) => Module.merge(meshes, weld, atol, sourceTag, dataPolicy, dropDuplicateCells),
        transform: (mesh, matrix, rotateVectorData = false) =>
            Module.transform(mesh, matrix, rotateVectorData),
        clean: (
            mesh,
            weld = false,
            atol = 1e-8,
            removeOrphans = true,
            dropDegenerate = true,
            dropDuplicateCells = true,
        ) => Module.clean(mesh, weld, atol, removeOrphans, dropDegenerate, dropDuplicateCells),
        // A negative `lambda` means "this method's own default" (0.5 Laplacian,
        // 0.33 Taubin) and is forwarded unchanged; the frozen-node mask is not
        // exposed here, as on the other flat bindings.
        smooth: (
            mesh,
            method = 'taubin',
            iterations = 10,
            lambda = -1,
            mu = -0.34,
            fixBoundary = true,
            preserveFeatures = true,
            featureAngle = 30,
            guardInversion = true,
        ) =>
            Module.smooth(
                mesh,
                method,
                iterations,
                lambda,
                mu,
                fixBoundary,
                preserveFeatures,
                featureAngle,
                guardInversion,
            ),
        // Cross-mesh field transfer: source point_data sampled at the target's
        // points, source cell_data by nearest source-cell centroid regardless
        // of the method. An empty `arrays` = every source point_data array.
        interpolate: (
            source,
            target,
            method = 'nearest',
            arrays = [],
            extrapolate = false,
            defaultValue = 0,
            onConflict = 'error',
        ) =>
            Module.interpolate(
                source,
                target,
                method,
                arrays,
                extrapolate,
                defaultValue,
                onConflict,
            ),
        // Mass-preserving cross-mesh field transfer: an exact overlap-measure
        // weighted remap (unlike interpolate's pointwise sampling). An empty
        // `arrays` = every source point_data AND cell_data array.
        conservativeInterpolate: (
            source,
            target,
            arrays = [],
            defaultValue = 0,
            onConflict = 'error',
        ) =>
            Module.conservativeInterpolate(
                source,
                target,
                arrays,
                defaultValue,
                onConflict,
            ),
        // Restore `fine`'s transitional (green) cells to their coarse parent,
        // read verbatim from `coarse` (a lookup, not a reconstruction).
        undoGreen: (coarse, fine) => Module.undoGreen(coarse, fine),
        cropBbox: (mesh, lo, hi, mode = 'all', recordIds = false) =>
            Module.cropBbox(mesh, lo, hi, mode, recordIds),
        cropPlane: (mesh, point, normal, mode = 'all', recordIds = false) =>
            Module.cropPlane(mesh, point, normal, mode, recordIds),
        cropPredicate: (mesh, array, compare = '<', value = 0, recordIds = false) =>
            Module.cropPredicate(mesh, array, compare, value, recordIds),
        slice: (mesh, origin, normal, recordParentIds = false) =>
            Module.slice(mesh, origin, normal, recordParentIds),
        grid: (dims, origin = null, spacing = null, maxCells = 20000000) =>
            Module.grid(dims, origin, spacing, maxCells),
        voxelize: (
            mesh,
            resolution = null,
            cellSize = 0,
            bounds = null,
            padding = 0,
            paddingRelative = 0,
            fill = 'all',
            sign = 'pseudonormal',
            attachOccupancy = false,
            maxCells = 20000000,
            watertightCheck = 'warn',
        ) =>
            Module.voxelize(mesh, resolution, cellSize, bounds, padding, paddingRelative,
                fill, sign, attachOccupancy, maxCells, watertightCheck),
        surfaceWatertightCheck: (mesh) => Module.surfaceWatertightCheck(mesh),
        sampleDistance: (surface, points, sign = 'pseudonormal', band = 0, watertightCheck = 'warn') =>
            Module.sampleDistance(surface, points, sign, band, watertightCheck),
        distanceToSurface: (
            query,
            surface,
            sign = 'pseudonormal',
            location = 'corner',
            band = 0,
            recordInside = false,
            watertightCheck = 'warn',
        ) =>
            Module.distanceToSurface(query, surface, sign, location, band, recordInside,
                watertightCheck),
        computeSdf: (
            surface,
            structure = 'voxel',
            resolution = null,
            cellSize = 0,
            bounds = null,
            padding = 0,
            paddingRelative = 0.1,
            rootResolution = 8,
            maxDepth = 4,
            bandCells = 1,
            recordLevels = true,
            maxCells = 20000000,
            sign = 'pseudonormal',
            location = 'corner',
            band = 0,
            watertightCheck = 'warn',
        ) =>
            Module.computeSdf(surface, structure, resolution, cellSize, bounds, padding,
                paddingRelative, rootResolution, maxDepth, bandCells, recordLevels, maxCells,
                sign, location, band, watertightCheck),
        isosurface: (mesh, array, isovalues, component = -1, recordParentIds = false) =>
            Module.isosurface(
                mesh,
                array,
                Array.isArray(isovalues) ? isovalues : [isovalues],
                component,
                recordParentIds,
            ),
        gradient: (
            mesh,
            array,
            operator = 'gradient',
            method = 'green-gauss',
            location = 'cell',
            output = '',
            component = -1,
            overwrite = false,
        ) =>
            Module.gradient(mesh, array, operator, method, location, output, component, overwrite),
        hessian: (
            mesh,
            array,
            method = 'green-gauss',
            location = 'cell',
            output = '',
            overwrite = false,
        ) => Module.hessian(mesh, array, method, location, output, overwrite),
        estimateError: (
            mesh,
            array,
            method = 'zz',
            marking = 'none',
            markingValue = 0.0,
            output = '',
            marked = '',
            overwrite = false,
        ) =>
            Module.estimateError(
                mesh,
                array,
                method,
                marking,
                markingValue,
                output,
                marked,
                overwrite,
            ),
        remesh: (
            mesh,
            numClusters,
            subdivide = -1,
            subsampleRatio = 10.0,
            maxSubdivide = 4,
            maxIterations = 100,
            maxRepairPasses = 10,
            metric = 'isotropic',
            gradation = 0.0,
            preserveBoundary = true,
        ) =>
            Module.remesh(
                mesh,
                numClusters,
                subdivide,
                subsampleRatio,
                maxSubdivide,
                maxIterations,
                maxRepairPasses,
                metric,
                gradation,
                preserveBoundary,
            ),
        split: (mesh, by, tagName = '') => Module.split(mesh, by, tagName),
        convertCells: (mesh, mode = 'linearize', recordParentIds = false) =>
            Module.convertCells(mesh, mode, recordParentIds),
        subdivide: (mesh, recordParentIds = false) => Module.subdivide(mesh, recordParentIds),
        agglomerate: (mesh, targetGroupSize = 8) => Module.agglomerate(mesh, targetGroupSize),
        refine: (mesh, levels = 1, recordParentIds = false, options = undefined) =>
            Module.refine(mesh, levels, recordParentIds, options),
        // Exactly one of ratio / targetFaces / maxError must be non-negative;
        // the frozen mask is not exposed here, as on the other flat bindings.
        decimate: (
            mesh,
            ratio = -1,
            targetFaces = -1,
            maxError = -1,
            placement = 'optimal',
            preserveBoundary = true,
            preserveFeatures = true,
            featureAngle = 30,
        ) =>
            Module.decimate(
                mesh,
                ratio,
                targetFaces,
                maxError,
                placement,
                preserveBoundary,
                preserveFeatures,
                featureAngle,
            ),
        partition: (
            mesh,
            nparts,
            method = 'auto',
            imbalance = 0.03,
            mode = 'eco',
            seed = 0,
            recordIds = false,
            ghostLayers = 0,
            weightsKey = '',
        ) =>
            Module.partition(
                mesh,
                nparts,
                method,
                imbalance,
                mode,
                seed,
                recordIds,
                ghostLayers,
                weightsKey,
            ),
        partitionLabels: (
            mesh,
            nparts,
            method = 'auto',
            imbalance = 0.03,
            mode = 'eco',
            seed = 0,
            weightsKey = '',
        ) => Module.partitionLabels(mesh, nparts, method, imbalance, mode, seed, weightsKey),
        stats: (mesh) => Module.stats(mesh),
        // Data operations (see doc/data_operations.md): act on point_data /
        // cell_data / field_data only -- the geometry is never modified.
        dataDrop: (mesh, location, names = [], ignoreMissing = false) =>
            Module.dataDrop(mesh, location, names, ignoreMissing),
        dataKeep: (mesh, location, names = [], ignoreMissing = false) =>
            Module.dataKeep(mesh, location, names, ignoreMissing),
        dataRename: (mesh, location, from, to) => Module.dataRename(mesh, location, from, to),
        dataPointToCell: (mesh, names = [], suffix = '') =>
            Module.dataPointToCell(mesh, names, suffix),
        dataCellToPoint: (mesh, names = [], weight = 'uniform', suffix = '') =>
            Module.dataCellToPoint(mesh, names, weight, suffix),
        dataCalc: (mesh, expression, location, outputName, overwrite = false) =>
            Module.dataCalc(mesh, expression, location, outputName, overwrite),
        dataCondition: (
            mesh,
            location,
            names = [],
            mode = 'clamp',
            lo = 0,
            hi = 1,
            scope = 'component',
            nanPolicy = 'ignore',
            nanReplacement = 0,
            suffix = '',
        ) =>
            Module.dataCondition(
                mesh, location, names, mode, lo, hi, scope, nanPolicy, nanReplacement, suffix,
            ),
        dataInfo: (mesh) => Module.dataInfo(mesh),
        dataIntegrate: (mesh, arrays = []) => Module.dataIntegrate(mesh, arrays),
        // Transient (time-series) XDMF -- the one *stateful* thing in this API.
        // The raw binding is an opaque integer handle plus seven free
        // functions (see bindings/wasm/js_bindings.cpp for why it is not an
        // embind class_); this wrapper is the ergonomic face of it, so callers
        // never see the handle and never call an Emscripten `.delete()`.
        //
        // The `.xdmf` appears at close()/finalize(), or earlier at a flush() --
        // the collection element has to enclose every step -- and with
        // dataFormat 'HDF' the series is TWO files in the virtual FS: `<path>`
        // and its sibling `<path minus extension>.h5`. Copy BOTH out of
        // Module.FS. `mode: 'append'` continues a series already at `path`.
        createXdmfTimeSeriesWriter: (
            path,
            { dataFormat = 'HDF', gzipLevel = -1, mode = 'truncate', autoFlush = false } = {},
        ) => {
            const handle = Module.xdmfSeriesCreate(path, dataFormat, gzipLevel, mode, autoFlush);
            let open = true;
            return {
                writePointsCells: (mesh) => Module.xdmfSeriesWritePointsCells(handle, mesh),
                writeData: (time, mesh) => Module.xdmfSeriesWriteData(handle, time, mesh),
                // Raw solver arrays instead of a mesh; `components` gives the
                // per-entity width of any array that is not a scalar.
                writeDataArrays: (time, pointData, cellData = {}, components = {}) =>
                    Module.xdmfSeriesWriteDataArrays(handle, time, pointData, cellData, components),
                // Make the `.xdmf` readable now, without finalizing.
                flush: () => Module.xdmfSeriesFlush(handle),
                finalize: () => Module.xdmfSeriesFinalize(handle),
                numSteps: () => Module.xdmfSeriesNumSteps(handle),
                finalized: () => Module.xdmfSeriesFinalized(handle),
                // Safe to call twice; safe to call in a `finally`. Finalizes
                // explicitly first so a write failure is thrown rather than
                // swallowed by the C++ destructor (which must not throw).
                close: () => {
                    if (!open) return;
                    open = false;
                    try {
                        Module.xdmfSeriesFinalize(handle);
                    } finally {
                        Module.xdmfSeriesFree(handle);
                    }
                },
            };
        },
    };
}

export default loadMeshioPlusPlus;
