// Ergonomic wrapper around the raw Emscripten/embind glue generated by
// bindings_js/js_bindings.cpp (see ../../CMakeLists.txt's `if(EMSCRIPTEN)`
// block and ../../build/configure-wasm.sh). The raw glue (dist/
// meshioplusplus_wasm.mjs, built by CMake, not hand-written) exports a
// MODULARIZE=1 + EXPORT_ES6=1 factory function; this file wraps that
// factory so callers get:
//   - default parameters (`format = ''` to infer from the file extension,
//     matching the C++ side's `resolve_format`, instead of Emscripten's raw
//     embind functions which require every parameter explicitly);
//   - a `convert()` with a friendlier `{ inFormat, outFormat }` options bag
//     instead of two trailing positional strings;
//   - `Module.FS` passed through unwrapped, since virtual-filesystem access
//     is the one place this package intentionally stays close to the raw
//     Emscripten API (see the README's "Reading/writing files" section).
//
// Each call to loadMeshioPlusPlus() instantiates a fresh, independent WASM
// module instance (safe to call more than once, e.g. one per Web Worker).
import createRawModule from '../dist/meshioplusplus_wasm.mjs';

/**
 * @typedef {Object} CellBlock
 * @property {string} type - meshio++ cell type name (e.g. "triangle", "tetra10").
 * @property {Int32Array} data - flat, row-major connectivity (numCells * nodesPerCell).
 * @property {number} nodesPerCell
 */

/**
 * @typedef {Object} Mesh
 * @property {Float64Array} points - flat, row-major (numPoints * dim).
 * @property {number} dim - 2 or 3.
 * @property {CellBlock[]} cells
 * @property {Object<string, Float64Array>} [point_data]
 * @property {Object<string, Float64Array[]>} [cell_data] - one array per cell block, same order as `cells`.
 * @property {Object<string, Float64Array>} [field_data]
 */

/**
 * Instantiate a fresh meshio++ WASM module.
 *
 * @param {object} [moduleOverrides] - forwarded to the Emscripten module
 *   factory as-is (e.g. `{ locateFile: (p) => new URL(p, import.meta.url) }`
 *   if you need to relocate the `.wasm` binary for a bundler/CDN setup).
 * @returns {Promise<{
 *   FS: object,
 *   readMesh: (path: string, format?: string) => Mesh,
 *   writeMesh: (path: string, mesh: Mesh, format?: string) => void,
 *   convert: (inPath: string, outPath: string, options?: {inFormat?: string, outFormat?: string}) => void,
 *   numNodesPerCell: () => Object<string, number>,
 *   topologicalDimension: () => Object<string, number>,
 *   dataDrop: (mesh: Mesh, location: string, names?: string[], ignoreMissing?: boolean) => Mesh,
 *   dataKeep: (mesh: Mesh, location: string, names?: string[], ignoreMissing?: boolean) => Mesh,
 *   dataRename: (mesh: Mesh, location: string, from: string, to: string) => Mesh,
 *   dataPointToCell: (mesh: Mesh, names?: string[], suffix?: string) => Mesh,
 *   dataCellToPoint: (mesh: Mesh, names?: string[], weight?: string, suffix?: string) => Mesh,
 *   dataCalc: (mesh: Mesh, expression: string, location: string, outputName: string, overwrite?: boolean) => Mesh,
 *   dataCondition: (mesh: Mesh, location: string, names?: string[], mode?: string, lo?: number, hi?: number, scope?: string, nanPolicy?: string, nanReplacement?: number, suffix?: string) => Mesh,
 *   dataInfo: (mesh: Mesh) => object[],
 * }>}
 */
export async function loadMeshioPlusPlus(moduleOverrides = {}) {
    const Module = await createRawModule(moduleOverrides);
    return {
        FS: Module.FS,
        readMesh: (path, format = '') => Module.readMesh(path, format),
        writeMesh: (path, mesh, format = '') => Module.writeMesh(path, mesh, format),
        convert: (inPath, outPath, { inFormat = '', outFormat = '' } = {}) =>
            Module.convert(inPath, inFormat, outPath, outFormat),
        numNodesPerCell: () => Module.numNodesPerCell(),
        topologicalDimension: () => Module.topologicalDimension(),
        // Data operations (see doc/data_operations.md): act on point_data /
        // cell_data / field_data only -- the geometry is never modified.
        dataDrop: (mesh, location, names = [], ignoreMissing = false) =>
            Module.dataDrop(mesh, location, names, ignoreMissing),
        dataKeep: (mesh, location, names = [], ignoreMissing = false) =>
            Module.dataKeep(mesh, location, names, ignoreMissing),
        dataRename: (mesh, location, from, to) => Module.dataRename(mesh, location, from, to),
        dataPointToCell: (mesh, names = [], suffix = '') =>
            Module.dataPointToCell(mesh, names, suffix),
        dataCellToPoint: (mesh, names = [], weight = 'uniform', suffix = '') =>
            Module.dataCellToPoint(mesh, names, weight, suffix),
        dataCalc: (mesh, expression, location, outputName, overwrite = false) =>
            Module.dataCalc(mesh, expression, location, outputName, overwrite),
        dataCondition: (
            mesh,
            location,
            names = [],
            mode = 'clamp',
            lo = 0,
            hi = 1,
            scope = 'component',
            nanPolicy = 'ignore',
            nanReplacement = 0,
            suffix = '',
        ) =>
            Module.dataCondition(
                mesh, location, names, mode, lo, hi, scope, nanPolicy, nanReplacement, suffix,
            ),
        dataInfo: (mesh) => Module.dataInfo(mesh),
    };
}

export default loadMeshioPlusPlus;
