// Ergonomic wrapper around the raw Emscripten/embind glue generated by
// bindings_js/js_bindings.cpp (see ../../CMakeLists.txt's `if(EMSCRIPTEN)`
// block and ../../build/configure-wasm.sh). The raw glue (dist/
// meshioplusplus_wasm.mjs, built by CMake, not hand-written) exports a
// MODULARIZE=1 + EXPORT_ES6=1 factory function; this file wraps that
// factory so callers get:
//   - default parameters (`format = ''` to infer from the file extension,
//     matching the C++ side's `resolve_format`, instead of Emscripten's raw
//     embind functions which require every parameter explicitly);
//   - a `convert()` with a friendlier `{ inFormat, outFormat }` options bag
//     instead of two trailing positional strings;
//   - `Module.FS` passed through unwrapped, since virtual-filesystem access
//     is the one place this package intentionally stays close to the raw
//     Emscripten API (see the README's "Reading/writing files" section).
//
// Each call to loadMeshioPlusPlus() instantiates a fresh, independent WASM
// module instance (safe to call more than once, e.g. one per Web Worker).
import createRawModule from '../dist/meshioplusplus_wasm.mjs';

/**
 * @typedef {Object} CellBlock
 * @property {string} type - meshio++ cell type name (e.g. "triangle", "tetra10").
 * @property {Int32Array} data - flat, row-major connectivity (numCells * nodesPerCell).
 * @property {number} nodesPerCell
 */

/**
 * @typedef {Object} Mesh
 * @property {Float64Array} points - flat, row-major (numPoints * dim).
 * @property {number} dim - 2 or 3.
 * @property {CellBlock[]} cells
 * @property {Object<string, Float64Array>} [point_data]
 * @property {Object<string, Float64Array[]>} [cell_data] - one array per cell block, same order as `cells`.
 * @property {Object<string, Float64Array>} [field_data]
 */

/**
 * Instantiate a fresh meshio++ WASM module.
 *
 * @param {object} [moduleOverrides] - forwarded to the Emscripten module
 *   factory as-is (e.g. `{ locateFile: (p) => new URL(p, import.meta.url) }`
 *   if you need to relocate the `.wasm` binary for a bundler/CDN setup).
 * @returns {Promise<{
 *   FS: object,
 *   readMesh: (path: string, format?: string) => Mesh,
 *   readMeshSelective: (path: string, options?: {format?: string, pointsOnly?: boolean, arrays?: string[]}) => Mesh,
 *   readMetadata: (path: string, format?: string) => object,
 *   readerSupportsOptions: (format: string) => boolean,
 *   writeMesh: (path: string, mesh: Mesh, format?: string) => void,
 *   convert: (inPath: string, outPath: string, options?: {inFormat?: string, outFormat?: string}) => void,
 *   numNodesPerCell: () => Object<string, number>,
 *   topologicalDimension: () => Object<string, number>,
 *   meshBackend: () => string,
 *   extractSurface: (mesh: Mesh, recordParentIds?: boolean) => Mesh,
 *   extractSkin: (mesh: Mesh, linearize?: boolean) => Mesh,
 *   attachQuality: (mesh: Mesh) => Mesh,
 *   sniffFormat: (path: string) => string,
 *   reorder: (mesh: Mesh, method?: string) => object,
 *   computeBandwidth: (mesh: Mesh) => number,
 *   diff: (a: Mesh, b: Mesh, atol?: number, rtol?: number, unordered?: boolean) => object,
 *   meshesEqual: (a: Mesh, b: Mesh, atol?: number, rtol?: number, unordered?: boolean) => boolean,
 *   merge: (meshes: Mesh[], weld?: boolean, atol?: number, sourceTag?: boolean, dataPolicy?: string, dropDuplicateCells?: boolean) => Mesh,
 *   transform: (mesh: Mesh, matrix: number[], rotateVectorData?: boolean) => Mesh,
 *   clean: (mesh: Mesh, weld?: boolean, atol?: number, removeOrphans?: boolean, dropDegenerate?: boolean, dropDuplicateCells?: boolean) => Mesh,
 *   cropBbox: (mesh: Mesh, lo: number[], hi: number[], mode?: string, recordIds?: boolean) => Mesh,
 *   cropPlane: (mesh: Mesh, point: number[], normal: number[], mode?: string, recordIds?: boolean) => Mesh,
 *   split: (mesh: Mesh, by: string, tagName?: string) => {key: string, mesh: Mesh}[],
 *   convertCells: (mesh: Mesh, mode?: string, recordParentIds?: boolean) => Mesh,
 *   refine: (mesh: Mesh, levels?: number, recordParentIds?: boolean) => Mesh,
 *   stats: (mesh: Mesh) => object,
 *   dataDrop: (mesh: Mesh, location: string, names?: string[], ignoreMissing?: boolean) => Mesh,
 *   dataKeep: (mesh: Mesh, location: string, names?: string[], ignoreMissing?: boolean) => Mesh,
 *   dataRename: (mesh: Mesh, location: string, from: string, to: string) => Mesh,
 *   dataPointToCell: (mesh: Mesh, names?: string[], suffix?: string) => Mesh,
 *   dataCellToPoint: (mesh: Mesh, names?: string[], weight?: string, suffix?: string) => Mesh,
 *   dataCalc: (mesh: Mesh, expression: string, location: string, outputName: string, overwrite?: boolean) => Mesh,
 *   dataCondition: (mesh: Mesh, location: string, names?: string[], mode?: string, lo?: number, hi?: number, scope?: string, nanPolicy?: string, nanReplacement?: number, suffix?: string) => Mesh,
 *   dataInfo: (mesh: Mesh) => object[],
 * }>}
 */
export async function loadMeshioPlusPlus(moduleOverrides = {}) {
    const Module = await createRawModule(moduleOverrides);
    return {
        FS: Module.FS,
        readMesh: (path, format = '') => Module.readMesh(path, format),
        // Selective reads (see doc/selective_read.md). `arrays: null` reads
        // every data array, `arrays: []` reads none -- the distinction is
        // deliberate. Formats without a native selective path are read whole
        // and filtered, so the result is the same either way.
        readMeshSelective: (path, { format = '', pointsOnly = false, arrays = null } = {}) =>
            Module.readMeshSelective(path, format, pointsOnly, arrays),
        // Summarize a file without loading its heavy arrays. The returned
        // object's `fellBackToFullRead` says whether that was actually cheap.
        readMetadata: (path, format = '') => Module.readMetadata(path, format),
        readerSupportsOptions: (format) => Module.readerSupportsOptions(format),
        writeMesh: (path, mesh, format = '') => Module.writeMesh(path, mesh, format),
        convert: (inPath, outPath, { inFormat = '', outFormat = '' } = {}) =>
            Module.convert(inPath, inFormat, outPath, outFormat),
        numNodesPerCell: () => Module.numNodesPerCell(),
        topologicalDimension: () => Module.topologicalDimension(),
        meshBackend: () => Module.meshBackend(),
        // Mesh operations (see doc/*.md per operation): computations ON a mesh,
        // not file formats. Index maps (crop/split/convertCells) are not carried
        // across the JS boundary -- use the record*Ids flags instead.
        extractSurface: (mesh, recordParentIds = false) =>
            Module.extractSurface(mesh, recordParentIds),
        extractSkin: (mesh, linearize = false) => Module.extractSkin(mesh, linearize),
        attachQuality: (mesh) => Module.attachQuality(mesh),
        sniffFormat: (path) => Module.sniffFormat(path),
        reorder: (mesh, method = 'rcm') => Module.reorder(mesh, method),
        computeBandwidth: (mesh) => Module.computeBandwidth(mesh),
        diff: (a, b, atol = 0, rtol = 0, unordered = false) =>
            Module.diff(a, b, atol, rtol, unordered),
        meshesEqual: (a, b, atol = 0, rtol = 0, unordered = false) =>
            Module.meshesEqual(a, b, atol, rtol, unordered),
        merge: (
            meshes,
            weld = false,
            atol = 1e-12,
            sourceTag = true,
            dataPolicy = 'intersection',
            dropDuplicateCells = false,
        ) => Module.merge(meshes, weld, atol, sourceTag, dataPolicy, dropDuplicateCells),
        transform: (mesh, matrix, rotateVectorData = false) =>
            Module.transform(mesh, matrix, rotateVectorData),
        clean: (
            mesh,
            weld = false,
            atol = 1e-12,
            removeOrphans = true,
            dropDegenerate = true,
            dropDuplicateCells = true,
        ) => Module.clean(mesh, weld, atol, removeOrphans, dropDegenerate, dropDuplicateCells),
        cropBbox: (mesh, lo, hi, mode = 'all', recordIds = false) =>
            Module.cropBbox(mesh, lo, hi, mode, recordIds),
        cropPlane: (mesh, point, normal, mode = 'all', recordIds = false) =>
            Module.cropPlane(mesh, point, normal, mode, recordIds),
        split: (mesh, by, tagName = '') => Module.split(mesh, by, tagName),
        convertCells: (mesh, mode = 'linearize', recordParentIds = false) =>
            Module.convertCells(mesh, mode, recordParentIds),
        refine: (mesh, levels = 1, recordParentIds = false) =>
            Module.refine(mesh, levels, recordParentIds),
        partition: (
            mesh,
            nparts,
            method = 'auto',
            imbalance = 0.03,
            mode = 'eco',
            seed = 0,
            recordIds = false,
            ghostLayers = 0,
            weightsKey = '',
        ) =>
            Module.partition(
                mesh,
                nparts,
                method,
                imbalance,
                mode,
                seed,
                recordIds,
                ghostLayers,
                weightsKey,
            ),
        partitionLabels: (
            mesh,
            nparts,
            method = 'auto',
            imbalance = 0.03,
            mode = 'eco',
            seed = 0,
            weightsKey = '',
        ) => Module.partitionLabels(mesh, nparts, method, imbalance, mode, seed, weightsKey),
        stats: (mesh) => Module.stats(mesh),
        // Data operations (see doc/data_operations.md): act on point_data /
        // cell_data / field_data only -- the geometry is never modified.
        dataDrop: (mesh, location, names = [], ignoreMissing = false) =>
            Module.dataDrop(mesh, location, names, ignoreMissing),
        dataKeep: (mesh, location, names = [], ignoreMissing = false) =>
            Module.dataKeep(mesh, location, names, ignoreMissing),
        dataRename: (mesh, location, from, to) => Module.dataRename(mesh, location, from, to),
        dataPointToCell: (mesh, names = [], suffix = '') =>
            Module.dataPointToCell(mesh, names, suffix),
        dataCellToPoint: (mesh, names = [], weight = 'uniform', suffix = '') =>
            Module.dataCellToPoint(mesh, names, weight, suffix),
        dataCalc: (mesh, expression, location, outputName, overwrite = false) =>
            Module.dataCalc(mesh, expression, location, outputName, overwrite),
        dataCondition: (
            mesh,
            location,
            names = [],
            mode = 'clamp',
            lo = 0,
            hi = 1,
            scope = 'component',
            nanPolicy = 'ignore',
            nanReplacement = 0,
            suffix = '',
        ) =>
            Module.dataCondition(
                mesh, location, names, mode, lo, hi, scope, nanPolicy, nanReplacement, suffix,
            ),
        dataInfo: (mesh) => Module.dataInfo(mesh),
    };
}

export default loadMeshioPlusPlus;
