#!/usr/bin/env python3
"""Generate the TikZ mesh-icon for the meshio++ logo.

Builds a *real* triangulation of an organic "FE surface blob", colours every
triangle with a smooth blue->teal gradient (a faux finite-element field), and
emits it as TikZ ``\\fill``/``\\draw`` commands into ``_mesh_icon.tex`` (which
``logo.tex`` and ``logo-icon.tex`` ``\\input``).

Deterministic: the point sampling is seeded, so re-running reproduces the same
logo byte-for-byte. Requires only numpy + matplotlib (matplotlib.tri for the
Delaunay triangulation and masking; no scipy).

Run from anywhere::

    python gen_logo_tikz.py            # writes logo/_mesh_icon.tex

then compile with ``build.sh``.
"""

from __future__ import annotations

import os

import numpy as np
from matplotlib.tri import Triangulation

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "_mesh_icon.tex")

# Palette (RGB 0-255): deep blue -> bright teal.
BLUE = np.array([31, 78, 121], dtype=float)
TEAL = np.array([46, 196, 182], dtype=float)
EDGE = np.array([255, 255, 255], dtype=float)  # triangle edge colour (white)

SEED = 20260714
ICON_SIZE = 2.5  # cm, bounding box of the icon


def blob_radius(theta: np.ndarray) -> np.ndarray:
    """Smooth organic closed outline r(theta) (mean radius 1)."""
    return (
        1.0
        + 0.16 * np.sin(3.0 * theta + 0.4)
        + 0.10 * np.cos(5.0 * theta + 1.1)
        - 0.06 * np.sin(2.0 * theta)
    )


def inside(x: np.ndarray, y: np.ndarray) -> np.ndarray:
    """Boolean mask: points (x, y) within the blob outline."""
    theta = np.arctan2(y, x)
    r = np.hypot(x, y)
    return r <= blob_radius(theta)


def build_triangulation():
    rng = np.random.default_rng(SEED)

    # Interior: a jittered hex-ish grid, kept where inside the blob.
    n = 15
    gx, gy = np.meshgrid(np.linspace(-1.25, 1.25, n), np.linspace(-1.25, 1.25, n))
    gx = gx + 0.06 * rng.standard_normal(gx.shape)
    gy = gy + 0.06 * rng.standard_normal(gy.shape)
    gx, gy = gx.ravel(), gy.ravel()
    keep = inside(gx, gy)
    ix, iy = gx[keep], gy[keep]

    # Boundary ring: dense samples exactly on the outline for a clean edge.
    tb = np.linspace(0, 2 * np.pi, 90, endpoint=False)
    rb = blob_radius(tb)
    bx, by = rb * np.cos(tb), rb * np.sin(tb)

    x = np.concatenate([ix, bx])
    y = np.concatenate([iy, by])

    tri = Triangulation(x, y)
    # Mask triangles whose centroid falls outside the blob (concave regions).
    cx = x[tri.triangles].mean(axis=1)
    cy = y[tri.triangles].mean(axis=1)
    tri.set_mask(~inside(cx, cy))
    return tri, x, y


def to_icon_coords(x: np.ndarray, y: np.ndarray):
    """Map blob coords into a centred [0, ICON_SIZE]^2 box (y up)."""
    span = 2.0 * 1.32  # blob roughly spans [-1.32, 1.32]
    scale = ICON_SIZE / span
    return (x * scale + ICON_SIZE / 2.0), (y * scale + ICON_SIZE / 2.0)


def tri_colour(cy_norm: float) -> tuple[int, int, int]:
    """Interpolate blue->teal by normalised centroid height."""
    c = BLUE + (TEAL - BLUE) * cy_norm
    return tuple(int(round(v)) for v in c)


def main() -> None:
    tri, x, y = build_triangulation()
    px, py = to_icon_coords(x, y)

    tris = tri.triangles
    mask = tri.mask if tri.mask is not None else np.zeros(len(tris), dtype=bool)

    cy = y[tri.triangles].mean(axis=1)
    lo, hi = cy.min(), cy.max()

    lines = [
        "% Auto-generated by gen_logo_tikz.py -- do not edit by hand.",
        "% Triangulated 'FE blob' icon for the meshio++ logo.",
        "\\begin{scope}",
    ]
    # Filled triangles first (so white edges draw on top).
    for k, t in enumerate(tris):
        if mask[k]:
            continue
        cyn = float((cy[k] - lo) / (hi - lo)) if hi > lo else 0.5
        r, g, b = tri_colour(cyn)
        p = [(px[i], py[i]) for i in t]
        coords = " -- ".join(f"({vx:.4f},{vy:.4f})" for vx, vy in p)
        lines.append(
            f"  \\fill[fill={{rgb,255:red,{r};green,{g};blue,{b}}}] {coords} -- cycle;"
        )
    # White edges on top for the mesh look.
    er, eg, eb = (int(v) for v in EDGE)
    for k, t in enumerate(tris):
        if mask[k]:
            continue
        p = [(px[i], py[i]) for i in t]
        coords = " -- ".join(f"({vx:.4f},{vy:.4f})" for vx, vy in p)
        lines.append(
            f"  \\draw[line width=0.35pt,draw={{rgb,255:red,{er};green,{eg};blue,{eb}}}]"
            f" {coords} -- cycle;"
        )
    lines.append("\\end{scope}")
    lines.append("")

    with open(OUT, "w") as fh:
        fh.write("\n".join(lines))

    n_tri = int((~mask).sum())
    print(f"wrote {OUT}: {n_tri} triangles, {len(x)} vertices")


if __name__ == "__main__":
    main()
