"""A SEACAS/Cubit-shaped Exodus II fixture, written with netCDF4 directly.

meshio++'s own Exodus writer cannot produce this file: it emits no
``qa_records``, no ``eb_names`` and no side sets at all (see
``exodus/_exodus.py``'s ``write``). A round-trip test through that writer
therefore could never have caught the defect this fixture exists for -- the
reader used to *throw* on ``qa_records``, which every file SEACAS, Cubit or
Sierra writes carries, making the format unreadable wherever there is no Python
fallback to defer to (i.e. all of WASM).

So the fixture is hand-authored against the Exodus II spec's variable
conventions rather than generated by the library under test. It is built at test
time rather than committed as a binary: the layout stays reviewable as code, and
``netCDF4`` is already an ``importorskip`` dependency of the Exodus suite.

The geometry is two unit hexahedra side by side along x::

    z=1  3---4---5        node index = z*6 + y*3 + x
         |   |   |        block 1 ("steel")     = the x in [0,1] hex
    z=0  0---1---2        block 2 ("aluminium") = the x in [1,2] hex

Every element of the fixture is load-bearing for one of the behaviours under
test; see ``FIXTURE_FACTS`` for what each one pins.
"""

from __future__ import annotations

import numpy as np

#: What the fixture is built to prove, so a reader of a failing test can tell
#: which property was being asserted rather than re-deriving it from the file.
FIXTURE_FACTS = {
    "qa_records": "reading must not throw; they surface as mesh.info",
    "two_same_type_blocks": (
        "'steel' and 'aluminium' are both HEX8 -- they must stay distinguishable "
        "as separate Cell regions, not collapse into one"
    ),
    "node_sets": "'left'/'right' become Point regions, 1-based -> 0-based",
    "side_set": (
        "'loadface' becomes a Side region of (global cell, local facet) pairs, "
        "with the facet remapped from Exodus's side numbering"
    ),
    "time_steps": "3 steps with genuinely different nodal values, so a wrong step is visible",
}

#: Node coordinates: a 3x2x2 lattice, x fastest then y then z.
POINTS = np.array(
    [[x, y, z] for z in (0.0, 1.0) for y in (0.0, 1.0) for x in (0.0, 1.0, 2.0)],
    dtype=np.float64,
)


def _node(x: int, y: int, z: int) -> int:
    return z * 6 + y * 3 + x


#: The two hexahedra, in meshio++/VTK node order (bottom ring, then top ring).
HEXES = [
    [
        _node(*c)
        for c in [
            (0, 0, 0),
            (1, 0, 0),
            (1, 1, 0),
            (0, 1, 0),
            (0, 0, 1),
            (1, 0, 1),
            (1, 1, 1),
            (0, 1, 1),
        ]
    ],
    [
        _node(*c)
        for c in [
            (1, 0, 0),
            (2, 0, 0),
            (2, 1, 0),
            (1, 1, 0),
            (1, 0, 1),
            (2, 0, 1),
            (2, 1, 1),
            (1, 1, 1),
        ]
    ],
]

BLOCK_NAMES = ["steel", "aluminium"]
BLOCK_IDS = [100, 200]

#: Node sets: the two end faces, as 0-based node indices.
NODE_SETS = {
    "left": [_node(0, 0, 0), _node(0, 1, 0), _node(0, 0, 1), _node(0, 1, 1)],
    "right": [_node(2, 0, 0), _node(2, 1, 0), _node(2, 0, 1), _node(2, 1, 1)],
}
NODE_SET_IDS = [10, 20]

#: Side set: element 1 side 4 (its x=0 face) and element 2 side 2 (its x=2 face)
#: -- deliberately two *different* Exodus side numbers, so an identity mapping
#: from side number to facet index would produce a visibly wrong answer.
SIDE_SET_NAME = "loadface"
SIDE_SET_ID = 30
SIDE_SET_ELEMS = [1, 2]  # 1-based Exodus element ids
SIDE_SET_SIDES = [4, 2]  # 1-based Exodus side numbers

#: The expected (global cell, local facet) pairs after remapping. Exodus HEX8
#: side 4 = {4,1,5,8} (1-based) = the x-minimum face, which is meshio++ facet 0;
#: side 2 = {2,3,7,6} = meshio++ facet 1.
SIDE_SET_EXPECTED = [(0, 0), (1, 1)]

QA_RECORD = ["CUBIT", "15.2", "2024/01/01", "12:00:00"]

TIME_VALUES = [0.0, 0.5, 1.0]


#: Nodal field: ``temperature = x + 10*t``. Chosen so every step is distinct and
#: the value alone identifies which step was read.
def temperature_at(step: int) -> np.ndarray:
    return POINTS[:, 0] + 10.0 * step


def write_fixture(path) -> str:
    """Write the fixture to `path` and return it as a string.

    Requires ``netCDF4``; callers are expected to have run
    ``pytest.importorskip("netCDF4")`` already.
    """
    import netCDF4

    path = str(path)
    with netCDF4.Dataset(path, "w", format="NETCDF3_CLASSIC") as nc:
        nc.title = "meshio++ test fixture (SEACAS-shaped)"
        nc.version = np.float32(5.1)
        nc.api_version = np.float32(5.1)
        nc.floating_point_word_size = 8

        nc.createDimension("num_nodes", len(POINTS))
        nc.createDimension("num_dim", 3)
        nc.createDimension("num_elem", len(HEXES))
        nc.createDimension("num_el_blk", len(HEXES))
        nc.createDimension("num_node_sets", len(NODE_SETS))
        nc.createDimension("num_side_sets", 1)
        nc.createDimension("len_string", 33)
        nc.createDimension("len_line", 81)
        nc.createDimension("four", 4)
        nc.createDimension("time_step", None)
        nc.createDimension("num_qa_rec", 1)

        # The variable that used to make this file unreadable.
        qa = nc.createVariable("qa_records", "S1", ("num_qa_rec", "four", "len_string"))
        _fill_names(qa, [QA_RECORD])

        nc.createVariable("coor_names", "S1", ("num_dim", "len_string"))
        nc.createVariable("coord", "f8", ("num_dim", "num_nodes"))[:] = POINTS.T

        # Element blocks. Both are HEX8: the names and ids are the only thing
        # keeping them apart, which is exactly what the region mapping must
        # preserve.
        nc.createVariable("eb_prop1", "i4", "num_el_blk")[:] = np.array(
            BLOCK_IDS, dtype=np.int32
        )
        _fill_names(
            nc.createVariable("eb_names", "S1", ("num_el_blk", "len_string")),
            BLOCK_NAMES,
        )
        for k, hexa in enumerate(HEXES):
            nc.createDimension(f"num_el_in_blk{k + 1}", 1)
            nc.createDimension(f"num_nod_per_el{k + 1}", 8)
            var = nc.createVariable(
                f"connect{k + 1}",
                "i4",
                (f"num_el_in_blk{k + 1}", f"num_nod_per_el{k + 1}"),
            )
            var.elem_type = "HEX8"
            var[:] = np.array([hexa], dtype=np.int32) + 1  # Exodus is 1-based

        # Node sets.
        nc.createVariable("ns_prop1", "i4", "num_node_sets")[:] = np.array(
            NODE_SET_IDS, dtype=np.int32
        )
        _fill_names(
            nc.createVariable("ns_names", "S1", ("num_node_sets", "len_string")),
            list(NODE_SETS),
        )
        for k, nodes in enumerate(NODE_SETS.values()):
            nc.createDimension(f"num_nod_ns{k + 1}", len(nodes))
            nc.createVariable(f"node_ns{k + 1}", "i4", (f"num_nod_ns{k + 1}",))[:] = (
                np.array(nodes, dtype=np.int32) + 1
            )

        # Side set.
        nc.createVariable("ss_prop1", "i4", "num_side_sets")[:] = np.array(
            [SIDE_SET_ID], dtype=np.int32
        )
        _fill_names(
            nc.createVariable("ss_names", "S1", ("num_side_sets", "len_string")),
            [SIDE_SET_NAME],
        )
        nc.createDimension("num_side_ss1", len(SIDE_SET_ELEMS))
        nc.createVariable("elem_ss1", "i4", ("num_side_ss1",))[:] = np.array(
            SIDE_SET_ELEMS, dtype=np.int32
        )
        nc.createVariable("side_ss1", "i4", ("num_side_ss1",))[:] = np.array(
            SIDE_SET_SIDES, dtype=np.int32
        )

        # Time series.
        nc.createVariable("time_whole", "f8", ("time_step",))[:] = np.array(
            TIME_VALUES, dtype=np.float64
        )
        nc.createDimension("num_nod_var", 1)
        _fill_names(
            nc.createVariable("name_nod_var", "S1", ("num_nod_var", "len_string")),
            ["temperature"],
        )
        vals = nc.createVariable("vals_nod_var1", "f8", ("time_step", "num_nodes"))
        for t in range(len(TIME_VALUES)):
            vals[t, :] = temperature_at(t)

    return path


def _fill_names(var, rows) -> None:
    """Fill a char variable one character at a time.

    netCDF's ``S1`` variables are arrays of single characters, so a string is
    written per-character. `rows` is either a list of strings (2-D variable) or
    a list of lists of strings (3-D, as ``qa_records`` is).
    """
    var.set_auto_mask(False)
    for i, row in enumerate(rows):
        if isinstance(row, str):
            for j, ch in enumerate(row):
                var[i, j] = ch.encode()
        else:
            for j, text in enumerate(row):
                for k, ch in enumerate(text):
                    var[i, j, k] = ch.encode()
