import pathlib

import numpy as np
import pytest

import meshioplusplus
from meshioplusplus import _core
from meshioplusplus.flux import _flux

from . import helpers


@pytest.mark.parametrize(
    "mesh",
    [
        helpers.line_mesh,
        helpers.tri_mesh,
        helpers.tri_mesh_2d,
        helpers.triangle6_mesh,
        helpers.quad_mesh,
        helpers.quad8_mesh,
        helpers.tet_mesh,
        helpers.tet10_mesh,
        helpers.hex_mesh,
        helpers.hex20_mesh,
        helpers.wedge_mesh,
    ],
)
def test_io(mesh, tmp_path):
    helpers.write_read(
        tmp_path, meshioplusplus.flux.write, meshioplusplus.flux.read, mesh, 1.0e-12
    )


def test_generic_io(tmp_path):
    helpers.generic_io(tmp_path / "test.pf3")
    helpers.generic_io(tmp_path / "test.0.pf3")


# Generated by tools/gen_feconv_quirk_fixtures.py in FLUX's own node layout.
MESHES = pathlib.Path(__file__).resolve().parent / "meshes" / "flux"

_READERS = [_core.flux_read, _flux.read]


@pytest.mark.parametrize("reader", _READERS, ids=["core", "python"])
def test_solids_read_positively_oriented(reader):
    mesh = reader(str(MESHES / "solids.pf3"))
    assert [c.type for c in mesh.cells] == [
        "tetra",
        "tetra10",
        "pyramid",
        "wedge",
        "wedge15",
        "hexahedron",
        "hexahedron20",
    ]
    helpers.assert_well_formed(mesh)


@pytest.mark.parametrize("reader", _READERS, ids=["core", "python"])
def test_truncated_file_keeps_what_it_holds(reader):
    mesh = reader(str(MESHES / "truncated.pf3"))
    assert len(mesh.points) == 8
    assert [c.type for c in mesh.cells] == ["quad8"]
    # Sparse ids 3, 121, 749, ... are numbered in row order.
    np.testing.assert_array_equal(mesh.cells[0].data, [[0, 1, 2, 3, 4, 5, 6, 7]])
    np.testing.assert_array_equal(mesh.cell_data["pf3:ref"][0], [4])
    helpers.assert_well_formed(mesh)


@pytest.mark.parametrize(
    "writer", [_core.flux_write, _flux.write], ids=["core", "python"]
)
def test_writer_mirrors_back(writer, tmp_path):
    mesh = _flux.read(MESHES / "solids.pf3")
    out = tmp_path / "out.pf3"
    writer(str(out), mesh)
    # Written in FLUX's layout: the connectivity rows equal the source file's.
    for a, b in zip(_flux.read(out).cells, mesh.cells):
        np.testing.assert_array_equal(a.data, b.data)
    raw = out.read_text(encoding="latin-1").split("COORDONNEES")[0]
    src = (MESHES / "solids.pf3").read_text(encoding="latin-1").split("COORDONNEES")[0]
    rows = [
        r.split()
        for r in raw.split("DESCRIPTEUR DE TOPOLOGIE DES ELEMENTS")[1].splitlines()
    ]
    srows = [
        r.split()
        for r in src.split("DESCRIPTEUR DE TOPOLOGIE DES ELEMENTS")[1].splitlines()
    ]
    assert rows[2::2] == srows[2::2]


def test_undefined_node_is_an_error(tmp_path):
    text = (MESHES / "truncated.pf3").read_text(encoding="latin-1")
    bad = tmp_path / "bad.pf3"
    bad.write_text(text.replace("   5329", "   9999", 1), encoding="latin-1")
    for reader in _READERS:
        with pytest.raises(meshioplusplus.ReadError):
            reader(str(bad))
