"""``_format_table`` agrees with what the format subpackages register.

``import meshioplusplus`` imports no format subpackage, so ``read`` and
``write`` find the one a path or a name needs through a static table
(roadmap §3.4.2). The table is generated by ``tools/gen_format_table.py`` from
the real ``register_format`` calls; a stale one would make a format
unreachable by extension until something else happened to import it.
"""

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def test_the_table_is_current():
    script = ROOT / "tools" / "gen_format_table.py"
    if not script.exists():
        return  # an installed copy of the tests, without the repository's tools
    result = subprocess.run(
        [sys.executable, str(script), "--check"], capture_output=True, text=True
    )
    assert result.returncode == 0, result.stdout + result.stderr


def test_every_registered_name_and_extension_is_in_the_table():
    code = (
        "import json\n"
        "import meshioplusplus\n"
        "from meshioplusplus import _format_table as t, _helpers as h\n"
        "h._load_all()\n"
        "names = set(dict.keys(h.reader_map)) | set(dict.keys(h._writer_map))\n"
        "exts = {e: list(v) for e, v in dict.items(h.extension_to_filetypes)}\n"
        "print(json.dumps({\n"
        "    'unknown_names': sorted(names - set(t.FORMAT_MODULES)),\n"
        "    'unknown_exts': sorted(set(exts) - set(t.EXTENSION_MODULES)),\n"
        "    'stale_names': sorted(n for n, m in t.FORMAT_MODULES.items()\n"
        "                          if m not in t.ALL_MODULES),\n"
        "    # An extension's candidates in the registry come from exactly the\n"
        "    # subpackages the table lists for it.\n"
        "    'wrong_owner': sorted(e for e, v in exts.items()\n"
        "                          if {t.FORMAT_MODULES[n] for n in v}\n"
        "                          != set(t.EXTENSION_MODULES[e])),\n"
        "}))\n"
    )
    out = subprocess.run(
        [sys.executable, "-c", code], check=True, capture_output=True, text=True
    )
    problems = json.loads(out.stdout.strip().splitlines()[-1])
    assert problems == {
        "unknown_names": [],
        "unknown_exts": [],
        "stale_names": [],
        "wrong_owner": [],
    }


def test_a_name_resolves_to_its_subpackage_alone():
    code = (
        "import json, sys\n"
        "import meshioplusplus\n"
        "from meshioplusplus import _helpers as h\n"
        "assert h._get_writer('gmsh22') is not None\n"
        "assert h._get_reader('marc_t19') is not None\n"
        "assert h._get_reader('no-such-format') is None\n"
        "print(json.dumps(sorted(n for n in ('gmsh', 'marc', 'stl', 'abaqus')\n"
        "                        if f'meshioplusplus.{n}' in sys.modules)))\n"
    )
    out = subprocess.run(
        [sys.executable, "-c", code], check=True, capture_output=True, text=True
    )
    assert json.loads(out.stdout.strip().splitlines()[-1]) == ["gmsh", "marc"]
