/**
 * @file colormap.hpp
 * @brief Built-in colormap lookup tables for data-driven SVG/TikZ coloring.
 *
 * Generated by tools/gen_colormaps.py -- do not edit by hand.
 *
 * Each colormap is a 256-entry table of packed uint8 RGB triples. viridis and
 * turbo are matplotlib's canonical 256-entry listed colormaps verbatim;
 * coolwarm is matplotlib's segmented map sampled at the same 256 points.
 *
 * Storing uint8 rather than float control points is deliberate. The SVG/TikZ
 * writers are pinned byte-for-byte against their pure-Python twins
 * (`tests/python/test_svg.py`, `tests/python/test_tikz.py`), and a float control-point table
 * would put a linear interpolation on every lookup that would then have to
 * round identically in C++ and in NumPy. With a full 256-entry table there is
 * nothing to interpolate: the entire floating-point surface of the color path
 * is the single index expression in colormap_lookup's body.
 *
 * The table data and function bodies live in `src/cpp/src/detail/colormap.cpp`,
 * not here -- this header is declarations only, so including it does not pull
 * three 768-byte array literals into every translation unit that colours a
 * face. The Python twin, which has no header/source split, is
 * `src/python/meshioplusplus/_colormap.py`; all three files are emitted by
 * `tools/gen_colormaps.py` and pinned against each other by
 * `tests/python/test_colormap.py`.
 */
#pragma once

#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

// Project includes
#include "meshioplusplus/export.hpp"

namespace meshioplusplus {
namespace detail {

/** @brief An 8-bit-per-channel RGB color. */
struct Rgb {
    std::uint8_t mR;
    std::uint8_t mG;
    std::uint8_t mB;
};

/// Entries per colormap table.
inline constexpr std::size_t kColormapSize = 256;

/**
 * @brief Look the named colormap's table up.
 * @param rName One of the names returned by colormap_names().
 * @return Pointer to `kColormapSize * 3` packed RGB bytes.
 * @throws std::invalid_argument if the name is not a built-in colormap.
 */
MESHIOPLUSPLUS_API const std::uint8_t* colormap_table(const std::string& rName);

/** @brief The built-in colormap names, in the documented order. */
MESHIOPLUSPLUS_API std::vector<std::string> colormap_names();

/**
 * @brief Map a normalized parameter to a color.
 * @param pTable A table from colormap_table().
 * @param t Position in the colormap; clamped to [0, 1]. NaN maps to the low end
 *          (callers route NaN to `nan_color` before reaching here).
 *
 * The index expression is the ONLY floating-point arithmetic in the color path,
 * and `src/python/meshioplusplus/_colormap.py` reproduces it character for character:
 * two IEEE-754 double operations in the same order, then a truncating cast.
 * Because `t` is non-negative here, truncation IS floor in both languages and
 * no tie-breaking is involved.
 *
 * Do NOT "improve" this to std::lround/std::round. Those round half away from
 * zero while Python's round() rounds half to even, and `t * 255.0 + 0.5` hits
 * exact ties at t = k/510 for small odd k -- values reachable from real data.
 */
MESHIOPLUSPLUS_API Rgb colormap_lookup(const std::uint8_t* pTable, double t);

}  // namespace detail
}  // namespace meshioplusplus
