import { defineConfig } from "vitepress";

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: "meshio++",
  description: "I/O for many mesh formats",
  // Project site served from https://loumalouomega.github.io/meshioplusplus/
  base: "/meshioplusplus/",
  lastUpdated: true,
  ignoreDeadLinks: true,

  head: [
    ["link", { rel: "icon", type: "image/svg+xml", href: "/meshioplusplus/logo-icon.svg" }],
    ["link", { rel: "alternate icon", type: "image/png", href: "/meshioplusplus/logo-icon.png" }],
    // Multi-resolution (16/32/48/64px) fallback for browsers/tools that only
    // look for a plain .ico (bookmark managers, old IE, some crawlers).
    ["link", { rel: "shortcut icon", type: "image/x-icon", href: "/meshioplusplus/favicon.ico" }],
  ],

  themeConfig: {
    logo: "/logo-icon.svg",

    nav: [
      { text: "Quickstart", link: "/quickstart" },
      { text: "Formats", link: "/formats" },
      { text: "Benchmarks", link: "/benchmarks" },
      { text: "CLI", link: "/cli" },
      { text: "Viewer", link: "/viewer/", target: "_self" },
      { text: "Dataset manager", link: "/viewer/dataset.html", target: "_self" },
      { text: "API (Doxygen)", link: "/api/", target: "_self" },
    ],

    sidebar: [
      {
        text: "Introduction",
        items: [
          { text: "Overview", link: "/" },
          { text: "Installation", link: "/installation" },
          { text: "Quickstart", link: "/quickstart" },
        ],
      },
      {
        text: "Concepts",
        items: [
          { text: "Mesh data model", link: "/mesh_data_model" },
          { text: "Named regions", link: "/regions" },
          { text: "C++ mesh backends", link: "/cpp_backends" },
          { text: "Cell types", link: "/cell_types" },
          { text: "Polyhedra and ragged cells", link: "/polyhedra" },
        ],
      },
      {
        text: "Reference",
        items: [
          { text: "Supported formats", link: "/formats" },
          { text: "Selective reads", link: "/selective_read" },
          { text: "Memory-mapped reading", link: "/mmap" },
          { text: "Compression codecs", link: "/codecs" },
          { text: "Mesh quality metrics", link: "/mesh_quality" },
          { text: "Surface extraction", link: "/extract_surface" },
          { text: "Skin extraction", link: "/extract_skin" },
          { text: "Reordering / renumbering", link: "/reorder" },
          { text: "Mesh comparison (diff)", link: "/diff" },
          { text: "Merge / combine", link: "/merge" },
          { text: "Affine transform", link: "/transform" },
          { text: "Clean (weld / prune)", link: "/clean" },
          { text: "Crop (bbox / half-space)", link: "/crop" },
          { text: "Split (by criterion)", link: "/split" },
          { text: "Partitioning (N parts)", link: "/partition" },
          { text: "Geometric statistics", link: "/stats" },
          { text: "Interactive viewer", link: "/viewer" },
          { text: "Interoperability", link: "/interop" },
          { text: "GPU handoff (DLPack / CuPy)", link: "/gpu" },
          { text: "ML data handling", link: "/ml" },
          { text: "Dataset manifests", link: "/datasets" },
          { text: "PhysicsNeMo integration", link: "/physicsnemo" },
          { text: "MCP server", link: "/mcp" },
          { text: "Cell conversion", link: "/convert_cells" },
          { text: "Polyhedral refinement (subdivide)", link: "/subdivide" },
          { text: "Polyhedral coarsening (agglomerate)", link: "/agglomerate" },
          { text: "Uniform refinement", link: "/refine" },
          { text: "Green-element undo", link: "/undo_green" },
          { text: "Decimation (QEM edge collapse)", link: "/decimate" },
          { text: "Volume decimation (QEM tet-edge collapse)", link: "/decimate_volume" },
          { text: "Surface remeshing (ACVD clustering)", link: "/remesh" },
          { text: "Volumetric remeshing (isosurface stuffing)", link: "/remesh_volume" },
          { text: "Smoothing (Laplacian / Taubin / ODT)", link: "/smooth" },
          { text: "Interpolation (field transfer)", link: "/interpolate" },
          { text: "Conservative interpolation (mass-preserving)", link: "/conservative_interpolate" },
          { text: "Slicing / cross-sections", link: "/slice" },
          { text: "Isosurfaces / contours", link: "/isosurface" },
          { text: "Regular grids / voxelize", link: "/voxelize" },
          { text: "Signed distance", link: "/sdf" },
          { text: "Field derivatives", link: "/gradient" },
          { text: "Error estimation", link: "/error" },
          { text: "Field integration", link: "/field_integration" },
          { text: "Second derivatives (Hessian)", link: "/hessian" },
          { text: "Data operations", link: "/data_operations" },
          { text: "· Array management", link: "/data_manage" },
          { text: "· Location averaging", link: "/data_average" },
          { text: "· Expressions (calc)", link: "/data_calc" },
          { text: "· Value conditioning", link: "/data_condition" },
          { text: "· Data summary", link: "/data_info" },
          { text: "Settings pipeline", link: "/pipeline" },
          { text: "Sequences (transient)", link: "/sequences" },
          { text: "CLI reference", link: "/cli" },
          { text: "XDMF time series", link: "/xdmf_time_series" },
          { text: "Extending meshio++", link: "/extending" },
          { text: "ParaView plugin", link: "/paraview_plugin" },
          { text: "WebAssembly / JavaScript", link: "/wasm" },
          { text: "Single-header C++", link: "/single_header" },
          { text: "C++ API", link: "/cpp_api" },
          { text: "C++ ABI compatibility", link: "/abi" },
          { text: "C API", link: "/c_api" },
          { text: "Fortran", link: "/fortran" },
          { text: "Julia", link: "/julia" },
          { text: "R", link: "/r" },
          { text: "Benchmarks", link: "/benchmarks" },
          { text: "API reference (Doxygen)", link: "/api/", target: "_self" },
        ],
      },
      {
        text: "Formats",
        collapsed: true,
        items: [
          { text: "abaqus", link: "/formats/abaqus" },
          { text: "ansys", link: "/formats/ansys" },
          { text: "ansysInp", link: "/formats/ansysinp" },
          { text: "avsucd", link: "/formats/avsucd" },
          { text: "cgns", link: "/formats/cgns" },
          { text: "dex", link: "/formats/dex" },
          { text: "dolfin-xml", link: "/formats/dolfin" },
          { text: "ensight", link: "/formats/ensight" },
          { text: "exodus", link: "/formats/exodus" },
          { text: "flac3d", link: "/formats/flac3d" },
          { text: "flux", link: "/formats/flux" },
          { text: "freefem", link: "/formats/freefem" },
          { text: "gmsh", link: "/formats/gmsh" },
          { text: "h5m", link: "/formats/h5m" },
          { text: "hmf", link: "/formats/hmf" },
          { text: "ip", link: "/formats/ip" },
          { text: "mdpa", link: "/formats/mdpa" },
          { text: "med", link: "/formats/med" },
          { text: "medit", link: "/formats/medit" },
          { text: "mff", link: "/formats/mff" },
          { text: "mfm", link: "/formats/mfm" },
          { text: "mphtxt", link: "/formats/mphtxt" },
          { text: "nastran", link: "/formats/nastran" },
          { text: "netgen", link: "/formats/netgen" },
          { text: "neuroglancer", link: "/formats/neuroglancer" },
          { text: "obj", link: "/formats/obj" },
          { text: "off", link: "/formats/off" },
          { text: "openfoam", link: "/formats/openfoam" },
          { text: "permas", link: "/formats/permas" },
          { text: "ply", link: "/formats/ply" },
          { text: "stl", link: "/formats/stl" },
          { text: "su2", link: "/formats/su2" },
          { text: "svg", link: "/formats/svg" },
          { text: "tecplot", link: "/formats/tecplot" },
          { text: "tetgen", link: "/formats/tetgen" },
          { text: "tikz", link: "/formats/tikz" },
          { text: "triangle", link: "/formats/triangle" },
          { text: "ugrid", link: "/formats/ugrid" },
          { text: "unv", link: "/formats/unv" },
          { text: "vti", link: "/formats/vti" },
          { text: "vtk", link: "/formats/vtk" },
          { text: "vtp", link: "/formats/vtp" },
          { text: "vtu", link: "/formats/vtu" },
          { text: "wkt", link: "/formats/wkt" },
          { text: "xdmf", link: "/formats/xdmf" },
        ],
      },
    ],

    socialLinks: [
      { icon: "github", link: "https://github.com/loumalouomega/meshioplusplus" },
    ],

    search: { provider: "local" },

    editLink: {
      pattern: "https://github.com/loumalouomega/meshioplusplus/edit/main/doc/:path",
    },

    footer: {
      message: "Released under the MIT License.",
      copyright: "meshio++ contributors",
    },
  },
});
