test_that("ordinary MED profiles expand to owning R data with NaN fill", {
  point_path <- Sys.getenv("MESHIOPLUSPLUS_TEST_MED_POINT_PROFILE")
  cell_path <- Sys.getenv("MESHIOPLUSPLUS_TEST_MED_CELL_PROFILE")
  skip_if_not(nzchar(point_path) && nzchar(cell_path), "generated MED profile fixtures not supplied")
  p <- mio_med_read_named(point_path, "mesh")
  c <- mio_med_read_named(cell_path, "mesh")
  on.exit({ mio_release(p); mio_release(c) })
  expect_equal(as.vector(mio_point_data(p, "pressure")), c(NaN, 5, NaN, 9))
  expect_equal(as.vector(mio_cell_data(c, "stress", 1L)), c(NaN, NaN, 9, 5))
})

test_that("pipeline Version 2 reaches terminal partition through report entry points", {
  skip_if_not(mio_pipeline_has_json())
  m <- fixture()
  dir <- tempfile("v2")
  dir.create(dir)
  on.exit({ mio_release(m); unlink(dir, recursive = TRUE) })
  input <- file.path(dir, "in.vtu")
  mio_write(m, input, codec = "none")
  text <- sprintf('{"Version":2,"Input":{"Path":"%s"},"Operations":[{"Op":"Merge","Inputs":["%s"]},{"Op":"Partition","Nparts":2,"Method":"sfc"}],"Output":{"Pattern":"%s/part_{part}.vtu","Codec":"none"}}', input, input, dir)
  report <- mio_pipeline_run_json_report(text)
  expect_match(report, '"op":"Merge"')
  expect_match(report, '"NumPieces":2')
  expect_true(file.exists(file.path(dir, "part_0.vtu")))
  expect_true(file.exists(file.path(dir, "part_1.vtu")))
})
