"""Built-in colormap lookup tables -- the twin of ``detail/colormap.hpp``/``.cpp``.

Generated by tools/gen_colormaps.py -- do not edit by hand.

Each colormap is a 256-entry table of packed uint8 RGB triples, identical byte
for byte to the C++ table (pinned by ``tests/python/test_colormap.py`` against the
``_core.colormap_table`` export). See the C++ header for why the tables are
stored as full 256-entry uint8 LUTs rather than as interpolated control points.
Python has no header/source split, so -- unlike the C++ side -- the data and
the functions both live in this one module.

Regenerate all three files with ``python tools/gen_colormaps.py``.
"""

from __future__ import annotations

COLORMAP_SIZE = 256

TABLES: dict[str, bytes] = {
    "viridis": bytes.fromhex(
        "44015444025645045745055946075a46085c460a5d460b5e470d60470e61471063471164"
        "47136548146748166848176948186a481a6c481b6d481c6e481d6f481f70482071482173"
        "482374482475482576482677482878482979472a7a472c7a472d7b472e7c472f7d46307e"
        "46327e46337f463480453581453781453882443983443a83443b84433d84433e85423f85"
        "4240864241864142874144874045884046883f47883f48893e49893e4a893e4c8a3d4d8a"
        "3d4e8a3c4f8a3c508b3b518b3b528b3a538b3a548c39558c39568c38588c38598c375a8c"
        "375b8d365c8d365d8d355e8d355f8d34608d34618d33628d33638d32648e32658e31668e"
        "31678e31688e30698e306a8e2f6b8e2f6c8e2e6d8e2e6e8e2e6f8e2d708e2d718e2c718e"
        "2c728e2c738e2b748e2b758e2a768e2a778e2a788e29798e297a8e297b8e287c8e287d8e"
        "277e8e277f8e27808e26818e26828e26828e25838e25848e25858e24868e24878e23888e"
        "23898e238a8d228b8d228c8d228d8d218e8d218f8d21908d21918c20928c20928c20938c"
        "1f948c1f958b1f968b1f978b1f988b1f998a1f9a8a1e9b8a1e9c891e9d891f9e891f9f88"
        "1fa0881fa1881fa1871fa28720a38620a48621a58521a68522a78522a88423a98324aa83"
        "25ab8225ac8226ad8127ad8128ae8029af7f2ab07f2cb17e2db27d2eb37c2fb47c31b57b"
        "32b67a34b67935b77937b87838b9773aba763bbb753dbc743fbc7340bd7242be7144bf70"
        "46c06f48c16e4ac16d4cc26c4ec36b50c46a52c56954c56856c66758c7655ac8645cc863"
        "5ec96260ca6063cb5f65cb5e67cc5c69cd5b6ccd5a6ece5870cf5773d05675d05477d153"
        "7ad1517cd2507fd34e81d34d84d44b86d54989d5488bd6468ed64590d74393d74195d840"
        "98d83e9bd93c9dd93ba0da39a2da37a5db36a8db34aadc32addc30b0dd2fb2dd2db5de2b"
        "b8de29bade28bddf26c0df25c2df23c5e021c8e020cae11fcde11dd0e11cd2e21bd5e21a"
        "d8e219dae319dde318dfe318e2e418e5e419e7e419eae51aece51befe51cf1e51df4e61e"
        "f6e620f8e621fbe723fde725"
    ),
    "coolwarm": bytes.fromhex(
        "3b4cc03c4ec23d50c33e51c53f53c64055c84257c94358cb445acc455cce465ecf485fd1"
        "4961d24a63d34b64d54c66d64e68d84f69d9506bda516ddb536edd5470de5572df5673e0"
        "5875e15977e35a78e45b7ae55d7ce65e7de75f7fe86180e96282ea6384eb6485ec6687ed"
        "6788ee688aef6a8bef6b8df06c8ff16e90f26f92f37093f37295f47396f57597f67699f6"
        "779af7799cf87a9df87b9ff97da0f97ea1fa80a3fa81a4fb82a6fb84a7fc85a8fc86a9fc"
        "88abfd89acfd8badfd8caffe8db0fe8fb1fe90b2fe92b4fe93b5fe94b6ff96b7ff97b8ff"
        "98b9ff9abbff9bbcff9dbdff9ebeff9fbfffa1c0ffa2c1ffa3c2fea5c3fea6c4fea7c5fe"
        "a9c6fdaac7fdabc8fdadc9fdaec9fcafcafcb1cbfcb2ccfbb3cdfbb5cdfab6cefab7cff9"
        "b9d0f9bad0f8bbd1f8bcd2f7bed2f6bfd3f6c0d4f5c1d4f4c3d5f4c4d5f3c5d6f2c6d6f1"
        "c7d7f0c9d7f0cad8efcbd8eeccd9edcdd9eccedaebcfdaead1dae9d2dbe8d3dbe7d4dbe6"
        "d5dbe5d6dce4d7dce3d8dce2d9dce1dadce0dbdcdedcdddddddcdcdedcdbdfdbd9e0dbd8"
        "e1dad6e2dad5e3d9d3e4d9d2e5d8d1e6d7cfe7d7cee8d6cce9d5cbead5c9ead4c8ebd3c6"
        "ecd3c5edd2c3edd1c2eed0c0efcfbfefcebdf0cdbbf1cdbaf1ccb8f2cbb7f2cab5f2c9b4"
        "f3c8b2f3c7b1f4c6aff4c5adf5c4acf5c2aaf5c1a9f5c0a7f6bfa6f6bea4f6bda2f7bca1"
        "f7ba9ff7b99ef7b89cf7b79bf7b599f7b497f7b396f7b194f7b093f7af91f7ad90f7ac8e"
        "f7aa8cf7a98bf7a889f7a688f6a586f6a385f6a283f5a081f59f80f59d7ef59c7df49a7b"
        "f4987af39778f39577f39475f29274f29072f18f71f18d6ff08b6ef08a6cef886bee8669"
        "ee8468ed8366ec8165ec7f63eb7d62ea7b60e97a5fe9785de8765ce7745be67259e57058"
        "e46e56e36c55e36b54e26952e16751e0654fdf634ede614ddd5f4bdc5d4ada5a49d95847"
        "d85646d75445d65244d55042d44e41d24b40d1493fd0473dcf453ccd423bcc403acb3e38"
        "ca3b37c83836c73635c53334c43032c32e31c12b30c0282fbe242ebd1f2dbb1b2cba162b"
        "b8122ab70d28b50927b40426"
    ),
    "turbo": bytes.fromhex(
        "30123b32154333184a341b51351e5836215f37246638276d392a733a2d793b2f803c3286"
        "3d358b3e38913f3b973f3e9c4040a24143a74146ac4249b1424bb5434eba4451bf4454c3"
        "4456c74559cb455ccf455ed34661d64664da4666dd4669e0466be3476ee64771e94773eb"
        "4776ee4778f0477bf2467df44680f64682f84685fa4687fb458afc458cfd448ffe4391fe"
        "4294ff4196ff4099ff3e9bfe3d9efe3ba0fd3aa3fc38a5fb37a8fa35abf833adf731aff5"
        "2fb2f42eb4f22cb7f02ab9ee28bceb27bee925c0e723c3e422c5e220c7df1fc9dd1ecbda"
        "1ccdd81bd0d51ad2d21ad4d019d5cd18d7ca18d9c818dbc518ddc218dec018e0bd19e2bb"
        "19e3b91ae4b61ce6b41de7b21fe9af20eaac22ebaa25eca727eea42aefa12cf09e2ff19b"
        "32f29835f39438f4913cf58e3ff68a43f78746f8844af8804ef97d52fa7a55fa7659fb73"
        "5dfc6f61fc6c65fd6969fd666dfe6271fe5f75fe5c79fe597dff5680ff5384ff5188ff4e"
        "8bff4b8fff4992ff4796fe4499fe429cfe409ffd3fa1fd3da4fc3ca7fc3aa9fb39acfb38"
        "affa37b1f936b4f836b7f735b9f635bcf534bef434c1f334c3f134c6f034c8ef34cbed34"
        "cdec34d0ea34d2e935d4e735d7e535d9e436dbe236dde037dfdf37e1dd37e3db38e5d938"
        "e7d739e9d539ebd339ecd13aeecf3aefcd3af1cb3af2c93af4c73af5c53af6c33af7c13a"
        "f8be39f9bc39faba39fbb838fbb637fcb336fcb136fdae35fdac34fea933fea732fea431"
        "fea130fe9e2ffe9b2dfe992cfe962bfe932afe9029fd8d27fd8a26fc8725fc8423fb8122"
        "fb7e21fa7b1ff9781ef9751df8721cf76f1af66c19f56918f46617f36315f26014f15d13"
        "f05b12ef5811ed5510ec530feb500eea4e0de84b0ce7490ce5470be4450ae2430ae14109"
        "df3f08dd3d08dc3b07da3907d83706d63506d43305d23105d02f05ce2d04cc2b04ca2a04"
        "c82803c52603c32503c12302be2102bc2002b91e02b71d02b41b01b21a01af1801ac1701"
        "a91601a71401a41301a112019e10019b0f01980e01950d01920b018e0a018b0902880802"
        "8507028106027e05027a0403"
    ),
}

NAMES = list(TABLES)


def colormap_table(name: str) -> bytes:
    """Return the named colormap's ``COLORMAP_SIZE * 3`` packed RGB bytes."""
    try:
        return TABLES[name]
    except KeyError:
        raise ValueError(
            f"meshio++: unknown colormap {name!r} (available: viridis, coolwarm, turbo)"
        ) from None


def colormap_lookup(table: bytes, t: float) -> tuple[int, int, int]:
    """Map a normalized parameter to an ``(r, g, b)`` triple.

    ``t`` is clamped to ``[0, 1]``; NaN maps to the low end (callers route NaN
    to ``nan_color`` before reaching here).

    The index expression is the ONLY floating-point arithmetic in the color
    path and reproduces ``detail::colormap_lookup`` character for character:
    two IEEE-754 double operations in the same order, then a truncating cast.
    Because ``t`` is non-negative here, ``int()`` truncation IS floor -- exactly
    as ``static_cast<int>`` is in C++ -- and no tie-breaking is involved.

    Do NOT "improve" this to ``round()``. Python rounds half to even while C++
    ``std::lround`` rounds half away from zero, and ``t * 255.0 + 0.5`` hits
    exact ties at ``t = k / 510`` for small odd ``k`` -- values reachable from
    real data.
    """
    t = float(t)
    if not (t > 0.0):  # also catches NaN
        t = 0.0
    if t > 1.0:
        t = 1.0
    i = int(t * 255.0 + 0.5)
    return table[i * 3], table[i * 3 + 1], table[i * 3 + 2]
