"""The browser backend of :func:`~meshioplusplus.view`.

Renders a mesh with the vtk.js app from ``src/viewer/``, either inline in a
notebook or in the default browser. Nothing is uploaded and no server is
started: the page is a single self-contained HTML file shipped inside the
wheel, with the mesh embedded in it.

Why the page carries no WebAssembly. The public demo at ``src/viewer/`` reads
arbitrary formats through the meshio++ WASM build, but here Python already
*has* the C++ core and can write the payload itself — so the browser only has
to render. ``src/viewer/`` is therefore built twice from one source, and this
build drops the worker and the ~2 MB ``.wasm``. Being a single file is also
what lets it open over ``file://`` with no local HTTP server.

The payload is **VTP**, not VTU: vtk.js ships no unstructured-grid model at all
(``vtkPolyData`` is its only mesh type), so a volume mesh is rendered by its
boundary surface. :func:`_renderable_surface` below is the Python twin of the
WASM build's ``convertSurface`` binding, and the two must agree — a mesh should
look the same whether it arrived through Python or through the demo.

Public API:

* :func:`view_browser` — render a mesh and open or display the page.
"""

from __future__ import annotations

import base64
import html
import json
import tempfile
import webbrowser
from io import BytesIO
from pathlib import Path
from typing import Optional

from ._common import warn

#: The built single-file viewer, regenerated by `src/viewer/`'s `build:embed`
#: script. See src/viewer/README.md.
_ASSET = Path(__file__).parent / "_viewer_assets" / "viewer.html"

#: The element `src/viewer/index.html` reserves for the mesh. A dedicated element
#: with a stable id survives minification, where a token inside a JS string
#: literal would not.
_PAYLOAD_SLOT = (
    '<script type="application/octet-stream;base64" id="vtp-payload"></script>'
)

#: Geometric statistics of the *volume* mesh. The page renders only the
#: boundary, so it could not derive these itself however long it looked.
_STATS_SLOT = '<script type="application/json" id="stats-payload"></script>'

#: Which array to colour by on load.
_CONFIG_SLOT = '<script type="application/json" id="view-config"></script>'

#: Above this, a base64 page becomes slow to hand to a browser (base64 is
#: 1.33x, and the whole document has to be parsed as one string).
_DEFAULT_MAX_MB = 64


def _renderable_surface(mesh, kind: str):
    """The part of ``mesh`` a surface renderer can actually draw.

    The Python twin of the WASM ``convertSurface`` binding, and it must stay in
    step with it: a mesh should look the same whether it reached the viewer
    through Python or through the hosted demo.

    A mesh with 3D cells becomes its boundary, anything else passes through,
    and the result is linearized — a triangle renderer has no concept of a
    mid-side node, so ``triangle6`` connectivity drawn verbatim is visible
    garbage rather than a curved triangle.
    """
    import numpy as np

    from ._convert_cells import _LINEAR_BASE, convert_cells
    from ._surface import extract_surface

    if kind not in ("auto", "surface"):
        raise ValueError(
            f"meshio++: view: backend='browser' cannot render kind='{kind}'; "
            "vtk.js has no volume mesh type, so only a surface can be drawn"
        )

    if not any(blk.dim == 3 for blk in mesh.cells):
        if any(blk.type in _LINEAR_BASE for blk in mesh.cells):
            return convert_cells(mesh, "linearize")
        return mesh

    # record_parent_ids, then gather: extract_surface drops cell data, but for
    # a viewer the useful answer is the owning cell's value -- colouring a
    # solid by its per-cell material or tag is the common case.
    from ._viewer import _flatten_cell_data

    surface = extract_surface(mesh, record_parent_ids=True)
    parents = [
        np.asarray(a).reshape(-1) for a in surface.cell_data["surface:parent_cell"]
    ]
    notes: list = []
    for name in mesh.cell_data:
        flat = _flatten_cell_data(mesh, name, notes)
        if flat is None:
            continue
        surface.cell_data[name] = [flat[p] for p in parents]
    # The parent ids are plumbing, not something to colour by.
    del surface.cell_data["surface:parent_cell"]

    if any(blk.type in _LINEAR_BASE for blk in surface.cells):
        surface = convert_cells(surface, "linearize")
    return surface


def _mesh_to_vtp(mesh) -> bytes:
    """Serialize a renderable mesh to VTP in memory."""
    buf = BytesIO()
    from ._helpers import write

    write(buf, mesh, file_format="vtp")
    return buf.getvalue()


def _in_notebook() -> bool:
    """Whether we are in a Jupyter kernel that can display HTML.

    Checks the shell *class*, not merely that ``get_ipython()`` returns
    something: terminal IPython gives a ``TerminalInteractiveShell``, where an
    iframe renders as nothing at all.
    """
    try:
        from IPython import get_ipython

        return type(get_ipython()).__name__ == "ZMQInteractiveShell"
    except Exception:
        return False


def _color_key(mesh, name: str) -> str:
    """The viewer's colour-by key for ``name``, or raise listing what exists.

    The key format (``location:name:component``, ``-1`` meaning magnitude) is
    the viewer's, mirrored here so a caller can name an array rather than
    having to know it.
    """
    if name in mesh.point_data:
        return f"point:{name}:-1"
    if name in mesh.cell_data:
        return f"cell:{name}:-1"
    available = ", ".join(sorted([*mesh.point_data, *mesh.cell_data])) or "none"
    raise ValueError(
        f"meshio++: view: no data array named '{name}' (available: {available})"
    )


def _fill_slot(page: str, slot: str, tag_id: str, content: str) -> str:
    """Substitute one payload slot, or fail naming it.

    The slots are matched as exact strings, so a viewer built from a different
    `index.html` must fail loudly here rather than silently produce a page that
    ignores half of what it was given.
    """
    if slot not in page:
        raise RuntimeError(
            f"meshio++: view: the bundled browser viewer has no '{tag_id}' slot; "
            "it was built from an incompatible src/viewer/index.html"
        )
    opening = slot[: slot.index("></script>") + 1]
    return page.replace(slot, f"{opening}{content}</script>")


def build_page(
    mesh,
    kind: str = "auto",
    title: str = "mesh",
    *,
    quality: bool = False,
    stats: bool = True,
    color_by: Optional[str] = None,
) -> str:
    """Return a self-contained HTML page displaying ``mesh``.

    Pure: writes no file, opens nothing. Split out from :func:`view_browser` so
    it can be tested without a browser.

    The page has no WebAssembly, so it cannot *run* meshio++ — anything it
    should be able to show has to be computed here and baked in.

    Parameters
    ----------
    mesh :
        the mesh to display (unmodified).
    kind :
        ``"auto"`` or ``"surface"``.
    title :
        page/tab title.
    quality :
        attach per-cell quality metrics before extracting the boundary, so the
        page can colour by them. Off by default: it adds around ten float
        arrays over the *volume* cells and can easily double the page size.
    stats :
        embed geometric statistics of the volume mesh. Sub-kilobyte, and the
        page renders only the boundary so it could not derive them itself.
    color_by :
        name of a data array to colour by on load. Raises if it does not exist,
        rather than warning — the mesh is right here to check against.
    """
    if not _ASSET.exists():
        raise RuntimeError(
            "meshio++: view: the bundled browser viewer is missing "
            f"({_ASSET}). It is generated by `cd src/viewer && npm run build:embed`; "
            "see src/viewer/README.md."
        )

    if quality:
        from ._quality import attach_quality

        # Before the boundary extraction, so the existing parent-id gather in
        # `_renderable_surface` carries the metrics onto the surface for free.
        mesh = attach_quality(mesh)

    key = _color_key(mesh, color_by) if color_by is not None else None

    payload = base64.b64encode(_mesh_to_vtp(_renderable_surface(mesh, kind)))
    page = _ASSET.read_text(encoding="utf-8")
    page = _fill_slot(page, _PAYLOAD_SLOT, "vtp-payload", payload.decode("ascii"))

    if stats:
        from ._stats import compute_stats

        summary = compute_stats(mesh)
        rows = {
            "Bounding box": _fmt_box(summary),
            "Surface area": f"{summary['total_area']:.6g}",
            "Volume": f"{summary['unsigned_volume']:.6g}",
        }
        if summary.get("num_inverted"):
            rows["Inverted cells"] = str(summary["num_inverted"])
        page = _fill_slot(page, _STATS_SLOT, "stats-payload", json.dumps(rows))

    if key is not None:
        page = _fill_slot(
            page, _CONFIG_SLOT, "view-config", json.dumps({"colorBy": key})
        )

    return page.replace(
        "<title>meshio++ viewer</title>", f"<title>{html.escape(title)}</title>"
    )


def _fmt_box(summary) -> str:
    lo, hi = summary["bbox_min"], summary["bbox_max"]
    fmt = lambda v: ", ".join(f"{x:.4g}" for x in v)  # noqa: E731
    return f"[{fmt(lo)}] … [{fmt(hi)}]"


def view_browser(
    mesh,
    kind: str = "auto",
    color_by: Optional[str] = None,
    title: str = "mesh",
    inline: Optional[bool] = None,
    max_mb: float = _DEFAULT_MAX_MB,
    *,
    quality: bool = False,
):
    """Render ``mesh`` with vtk.js and show it.

    Parameters
    ----------
    mesh :
        the mesh to show (unmodified).
    kind :
        ``"auto"`` or ``"surface"``. A volume mesh is always drawn by its
        boundary, so ``"volume"`` is rejected rather than silently ignored.
    color_by :
        name of a data array to colour by on load. Raises if it does not exist.
    title :
        page/tab title.
    inline :
        force inline display (``True``) or a browser window (``False``).
        Default: inline inside a Jupyter kernel, a browser window otherwise.
    max_mb :
        warn above this page size.

    Returns
    -------
    str or None
        the path of the generated page, or ``None`` when displayed inline.
    """
    page = build_page(mesh, kind=kind, title=title, quality=quality, color_by=color_by)
    size_mb = len(page) / 1e6
    if size_mb > max_mb:
        warn(
            f"view: this mesh makes a {size_mb:.0f} MB page, which browsers "
            "handle poorly; consider backend='polyscope' or a cropped mesh"
        )

    if inline is None:
        inline = _in_notebook()

    if inline:
        from IPython.display import HTML, display

        # A data: URL rather than srcdoc: srcdoc would need the whole
        # multi-megabyte document HTML-escaped, doubling it for nothing.
        encoded = base64.b64encode(page.encode("utf-8")).decode("ascii")
        display(
            HTML(
                f'<iframe src="data:text/html;base64,{encoded}" '
                'style="width:100%;height:600px;border:0;border-radius:6px"'
                ' allow="fullscreen"></iframe>'
            )
        )
        return None

    directory = Path(tempfile.mkdtemp(prefix="meshioplusplus-viewer-"))
    path = directory / "viewer.html"
    path.write_text(page, encoding="utf-8")
    webbrowser.open(path.as_uri())
    return str(path)
