#!/usr/bin/env python3
"""Generate the built-in colormap lookup tables.

meshio++'s SVG/TikZ data-driven coloring maps a scalar through a colormap
without taking a dependency on matplotlib: the tables are baked into the core
as 256-entry uint8 LUTs. viridis and turbo are *defined* by matplotlib as
256-entry listed colormaps, so the LUT is the canonical data rather than an
approximation; coolwarm is a segmented map sampled at the same 256 points
matplotlib itself renders it at.

Three files come out of this, and are pinned against each other by
``tests/python/test_colormap.py`` (via the ``_core.colormap_table`` export), so a
hand-edit to any one of them fails CI:

- ``src/cpp/include/meshioplusplus/detail/colormap.hpp`` -- declarations only
  (`Rgb`, `kColormapSize`, the three function signatures). No table data, so
  every translation unit that includes it stays cheap to compile.
- ``src/cpp/src/detail/colormap.cpp`` -- the table data (file-private, in an
  anonymous namespace) and the function bodies. Mirrors the rest of
  `src/cpp/src/detail/`: a body that runs once per call (`colormap_table`,
  `colormap_names`) or once per face (`colormap_lookup`, the same "once per
  cell" bucket `FiniteStats`'s neighbours in `data_ops.hpp` document) belongs
  out of line, not inlined into every including TU.
- ``src/python/meshioplusplus/_colormap.py`` -- the Python twin. Python has no
  header/source split, so this one file carries both the tables and the
  functions, as before.

Regenerate with::

    python tools/gen_colormaps.py

matplotlib is needed to *regenerate*; the committed output is dependency-free.
"""

from __future__ import annotations

import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent

# Order is the user-facing order in error messages and CLI --cmap choices.
NAMES = ["viridis", "coolwarm", "turbo"]

HPP_PATH = REPO / "cpp" / "include" / "meshioplusplus" / "detail" / "colormap.hpp"
CPP_PATH = REPO / "cpp" / "src" / "detail" / "colormap.cpp"
PY_PATH = REPO / "src" / "meshioplusplus" / "_colormap.py"

GENERATED = "Generated by tools/gen_colormaps.py -- do not edit by hand."

LICENSE_BANNER = """\
//  ██████   ██████ ██████████  █████████  █████   █████ █████    ███████
// ░░██████ ██████ ░░███░░░░░█ ███░░░░░███░░███   ░░███ ░░███   ███░░░░░███      ███         ███
//  ░███░█████░███  ░███  █ ░ ░███    ░░░  ░███    ░███  ░███  ███     ░░███    ░███        ░███
//  ░███░░███ ░███  ░██████   ░░█████████  ░███████████  ░███ ░███      ░███ ███████████ ███████████
//  ░███ ░░░  ░███  ░███░░█    ░░░░░░░░███ ░███░░░░░███  ░███ ░███      ░███░░░░░███░░░ ░░░░░███░░░
//  ░███      ░███  ░███ ░   █ ███    ░███ ░███    ░███  ░███ ░░███     ███     ░███        ░███
//  █████     █████ ██████████░░█████████  █████   █████ █████ ░░░███████░      ░░░         ░░░
// ░░░░░     ░░░░░ ░░░░░░░░░░  ░░░░░░░░░  ░░░░░   ░░░░░ ░░░░░    ░░░░░░░
//
//
//  License:         MIT License
//                   meshio++ default license: LICENSE
//
//  Main authors:    Vicente Mataix Ferrandiz
//
//
"""


def sample(name: str) -> bytes:
    """Sample `name` at the 256 canonical points, as packed RGB bytes."""
    import numpy as np
    from matplotlib import colormaps

    rgba = colormaps[name](np.linspace(0.0, 1.0, 256))
    rgb = np.round(rgba[:, :3] * 255.0).astype(np.uint8)
    return rgb.tobytes()


def cpp_array(name: str, table: bytes) -> str:
    ident = "k" + name.capitalize()
    rows = []
    for i in range(0, len(table), 12):
        rows.append("    " + ", ".join(str(b) for b in table[i : i + 12]) + ",")
    body = "\n".join(rows).rstrip(",")
    # clang-format would reflow the table into one value per line; the guards
    # keep the generated layout stable so `clang-format -i` is a no-op here.
    return (
        "// clang-format off\n"
        f"constexpr std::uint8_t {ident}[kColormapSize * 3] = {{\n{body}}};\n"
        "// clang-format on\n"
    )


def write_hpp() -> None:
    HPP_PATH.write_text(
        f"""/**
 * @file colormap.hpp
 * @brief Built-in colormap lookup tables for data-driven SVG/TikZ coloring.
 *
 * {GENERATED}
 *
 * Each colormap is a 256-entry table of packed uint8 RGB triples. viridis and
 * turbo are matplotlib's canonical 256-entry listed colormaps verbatim;
 * coolwarm is matplotlib's segmented map sampled at the same 256 points.
 *
 * Storing uint8 rather than float control points is deliberate. The SVG/TikZ
 * writers are pinned byte-for-byte against their pure-Python twins
 * (`tests/python/test_svg.py`, `tests/python/test_tikz.py`), and a float control-point table
 * would put a linear interpolation on every lookup that would then have to
 * round identically in C++ and in NumPy. With a full 256-entry table there is
 * nothing to interpolate: the entire floating-point surface of the color path
 * is the single index expression in colormap_lookup's body.
 *
 * The table data and function bodies live in `src/cpp/src/detail/colormap.cpp`,
 * not here -- this header is declarations only, so including it does not pull
 * three 768-byte array literals into every translation unit that colours a
 * face. The Python twin, which has no header/source split, is
 * `src/python/meshioplusplus/_colormap.py`; all three files are emitted by
 * `tools/gen_colormaps.py` and pinned against each other by
 * `tests/python/test_colormap.py`.
 */
#pragma once

#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

namespace meshioplusplus {{
namespace detail {{

/** @brief An 8-bit-per-channel RGB color. */
struct Rgb {{
    std::uint8_t mR;
    std::uint8_t mG;
    std::uint8_t mB;
}};

/// Entries per colormap table.
inline constexpr std::size_t kColormapSize = 256;

/**
 * @brief Look the named colormap's table up.
 * @param rName One of the names returned by colormap_names().
 * @return Pointer to `kColormapSize * 3` packed RGB bytes.
 * @throws std::invalid_argument if the name is not a built-in colormap.
 */
const std::uint8_t* colormap_table(const std::string& rName);

/** @brief The built-in colormap names, in the documented order. */
std::vector<std::string> colormap_names();

/**
 * @brief Map a normalized parameter to a color.
 * @param pTable A table from colormap_table().
 * @param t Position in the colormap; clamped to [0, 1]. NaN maps to the low end
 *          (callers route NaN to `nan_color` before reaching here).
 *
 * The index expression is the ONLY floating-point arithmetic in the color path,
 * and `src/python/meshioplusplus/_colormap.py` reproduces it character for character:
 * two IEEE-754 double operations in the same order, then a truncating cast.
 * Because `t` is non-negative here, truncation IS floor in both languages and
 * no tie-breaking is involved.
 *
 * Do NOT "improve" this to std::lround/std::round. Those round half away from
 * zero while Python's round() rounds half to even, and `t * 255.0 + 0.5` hits
 * exact ties at t = k/510 for small odd k -- values reachable from real data.
 */
Rgb colormap_lookup(const std::uint8_t* pTable, double t);

}}  // namespace detail
}}  // namespace meshioplusplus
"""
    )


def write_cpp(tables: dict[str, bytes]) -> None:
    arrays = "\n".join(cpp_array(n, tables[n]) for n in NAMES)
    branches = "\n".join(
        f'    if (rName == "{n}")\n        return k{n.capitalize()};' for n in NAMES
    )
    names_list = ", ".join(f'"{n}"' for n in NAMES)
    known = ", ".join(NAMES)

    CPP_PATH.write_text(
        f"""{LICENSE_BANNER}
// {GENERATED}
//
// The table data below is file-private (anonymous namespace): it is reachable
// only through colormap_table()/colormap_lookup(), so it never leaks into the
// symbols of a TU that merely includes colormap.hpp. See the header for why
// these bodies -- called once per write or once per face, never once per
// scalar -- live here rather than inline.

// System includes
#include <stdexcept>

// Project includes
#include "meshioplusplus/detail/colormap.hpp"

namespace meshioplusplus {{
namespace detail {{

namespace {{

{arrays}
}}  // namespace

const std::uint8_t* colormap_table(const std::string& rName) {{
{branches}
    throw std::invalid_argument("meshio++: unknown colormap '" + rName +
                                "' (available: {known})");
}}

std::vector<std::string> colormap_names() {{
    return {{{names_list}}};
}}

Rgb colormap_lookup(const std::uint8_t* pTable, double t) {{
    if (!(t > 0.0))  // also catches NaN
        t = 0.0;
    if (t > 1.0)
        t = 1.0;
    const int i = static_cast<int>(t * 255.0 + 0.5);
    return Rgb{{pTable[i * 3], pTable[i * 3 + 1], pTable[i * 3 + 2]}};
}}

}}  // namespace detail
}}  // namespace meshioplusplus
"""
    )


def write_py(tables: dict[str, bytes]) -> None:
    entries = "\n".join(
        f'    "{n}": bytes.fromhex(\n'
        + "\n".join(
            f'        "{tables[n].hex()[i : i + 72]}"'
            for i in range(0, len(tables[n].hex()), 72)
        )
        + "\n    ),"
        for n in NAMES
    )
    known = ", ".join(NAMES)

    PY_PATH.write_text(
        f'''"""Built-in colormap lookup tables -- the twin of ``detail/colormap.hpp``/``.cpp``.

{GENERATED}

Each colormap is a 256-entry table of packed uint8 RGB triples, identical byte
for byte to the C++ table (pinned by ``tests/python/test_colormap.py`` against the
``_core.colormap_table`` export). See the C++ header for why the tables are
stored as full 256-entry uint8 LUTs rather than as interpolated control points.
Python has no header/source split, so -- unlike the C++ side -- the data and
the functions both live in this one module.

Regenerate all three files with ``python tools/gen_colormaps.py``.
"""

from __future__ import annotations

COLORMAP_SIZE = 256

TABLES: dict[str, bytes] = {{
{entries}
}}

NAMES = list(TABLES)


def colormap_table(name: str) -> bytes:
    """Return the named colormap's ``COLORMAP_SIZE * 3`` packed RGB bytes."""
    try:
        return TABLES[name]
    except KeyError:
        raise ValueError(
            f"meshio++: unknown colormap {{name!r}} (available: {known})"
        ) from None


def colormap_lookup(table: bytes, t: float) -> tuple[int, int, int]:
    """Map a normalized parameter to an ``(r, g, b)`` triple.

    ``t`` is clamped to ``[0, 1]``; NaN maps to the low end (callers route NaN
    to ``nan_color`` before reaching here).

    The index expression is the ONLY floating-point arithmetic in the color
    path and reproduces ``detail::colormap_lookup`` character for character:
    two IEEE-754 double operations in the same order, then a truncating cast.
    Because ``t`` is non-negative here, ``int()`` truncation IS floor -- exactly
    as ``static_cast<int>`` is in C++ -- and no tie-breaking is involved.

    Do NOT "improve" this to ``round()``. Python rounds half to even while C++
    ``std::lround`` rounds half away from zero, and ``t * 255.0 + 0.5`` hits
    exact ties at ``t = k / 510`` for small odd ``k`` -- values reachable from
    real data.
    """
    t = float(t)
    if not (t > 0.0):  # also catches NaN
        t = 0.0
    if t > 1.0:
        t = 1.0
    i = int(t * 255.0 + 0.5)
    return table[i * 3], table[i * 3 + 1], table[i * 3 + 2]
'''
    )


def main() -> int:
    try:
        tables = {n: sample(n) for n in NAMES}
    except ImportError:
        print(
            "matplotlib is required to regenerate the colormap tables "
            "(the committed output itself is dependency-free)",
            file=sys.stderr,
        )
        return 1

    for name, table in tables.items():
        assert len(table) == 256 * 3, (name, len(table))

    write_hpp()
    write_cpp(tables)
    write_py(tables)
    print(f"wrote {HPP_PATH.relative_to(REPO)}")
    print(f"wrote {CPP_PATH.relative_to(REPO)}")
    print(f"wrote {PY_PATH.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
