#!/usr/bin/env python3
"""Generate the sRGB -> linear lookup table the glTF writer bakes colors with.

glTF's ``COLOR_0`` is *linear* RGB, while the colormap tables are 8-bit sRGB
display values, so a colormap must go through the inverse sRGB transfer function
before it is written -- otherwise every viewer brightens it. The transform needs
``pow``; a 256-entry table of float32 bit patterns instead makes the bytes the
writers emit independent of which libm either engine links, so the C++ and
Python writers stay byte-identical on every platform.

The table is spliced between ``BEGIN srgb_linear`` / ``END srgb_linear`` markers
in three files, pinned against each other by ``tests/python/test_colormap.py``::

    src/cpp/include/meshioplusplus/detail/colormap.hpp   (declaration)
    src/cpp/src/detail/colormap.cpp                      (data + accessor)
    src/python/meshioplusplus/_colormap.py               (data)

Regenerate with ``python tools/gen_srgb_linear.py``; it is idempotent and needs
nothing but the standard library.
"""

from __future__ import annotations

import pathlib
import re
import struct

REPO = pathlib.Path(__file__).resolve().parent.parent
HPP = REPO / "src/cpp/include/meshioplusplus/detail/colormap.hpp"
CPP = REPO / "src/cpp/src/detail/colormap.cpp"
PY = REPO / "src/python/meshioplusplus/_colormap.py"


def bits() -> list[int]:
    out = []
    for c in range(256):
        f = c / 255.0
        lin = f / 12.92 if f <= 0.04045 else ((f + 0.055) / 1.055) ** 2.4
        out.append(struct.unpack("<I", struct.pack("<f", lin))[0])
    return out


def _rows(values, per_line, fmt, indent):
    lines = []
    for i in range(0, len(values), per_line):
        lines.append(
            indent + ", ".join(fmt % v for v in values[i : i + per_line]) + ","
        )
    return "\n".join(lines)


def cpp_block() -> str:
    return (
        "// BEGIN srgb_linear -- generated by tools/gen_srgb_linear.py, do not edit\n"
        "// clang-format off\n"
        "const std::uint32_t kSrgbLinearBits[256] = {\n"
        + _rows(bits(), 8, "0x%08x", "    ")
        + "\n};\n"
        "// clang-format on\n"
        "// END srgb_linear\n"
    )


def hpp_block() -> str:
    return (
        "// BEGIN srgb_linear -- generated by tools/gen_srgb_linear.py, do not edit\n"
        "/**\n"
        " * @brief The inverse sRGB transfer function of every 8-bit value, as float32\n"
        " * bit patterns (256 entries): what a colormap byte becomes in glTF's linear\n"
        " * `COLOR_0`. A table, not a `pow`, so both engines emit identical bytes.\n"
        " */\n"
        "MESHIOPLUSPLUS_API const std::uint32_t* srgb_to_linear_bits();\n"
        "// END srgb_linear\n"
    )


def py_block() -> str:
    raw = struct.pack("<256I", *bits()).hex()
    rows = "\n".join(f'        "{raw[i : i + 72]}"' for i in range(0, len(raw), 72))
    return (
        "# BEGIN srgb_linear -- generated by tools/gen_srgb_linear.py, do not edit\n"
        "#: The inverse sRGB transfer function of every 8-bit value, as float32 bit\n"
        "#: patterns -- what a colormap byte becomes in glTF's linear ``COLOR_0``.\n"
        "SRGB_TO_LINEAR_BITS: tuple[int, ...] = struct.unpack(\n"
        '    "<256I",\n'
        "    bytes.fromhex(\n" + rows + "\n    ),\n"
        ")\n"
        "# END srgb_linear\n"
    )


def splice(path: pathlib.Path, block: str, anchor: str) -> None:
    text = path.read_text()
    pat = re.compile(r"(?:// |# )BEGIN srgb_linear.*?(?:// |# )END srgb_linear\n", re.S)
    if pat.search(text):
        text = pat.sub(lambda m: block, text)
    else:
        assert anchor in text, f"anchor missing in {path}"
        text = text.replace(anchor, block + "\n" + anchor, 1)
    path.write_text(text)


def main() -> None:
    splice(HPP, hpp_block(), "}  // namespace detail\n}  // namespace meshioplusplus")
    splice(CPP, cpp_block(), "}  // namespace\n\nconst std::uint8_t* colormap_table")
    splice(PY, py_block(), "def colormap_table(")


if __name__ == "__main__":
    main()
