#!/usr/bin/env python3
"""Regenerate ``src/python/meshioplusplus/_format_table.py``.

``import meshioplusplus`` does not import the format subpackages: each registers
its formats when it is imported, so ``read`` and ``write`` need to know, before
they can look anything up, which subpackage a file extension or a format name
belongs to. This script imports every format subpackage with
``_helpers.register_format`` instrumented, and writes what each registered.

    python tools/gen_format_table.py            # rewrite the table
    python tools/gen_format_table.py --check    # exit 1 if it is out of date

Run it after adding or changing a ``register_format`` call;
``tests/python/test_format_table.py`` fails until you do.
"""

from __future__ import annotations

import argparse
import importlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PACKAGE = ROOT / "src" / "python" / "meshioplusplus"
TABLE = PACKAGE / "_format_table.py"

# Subpackages that are not formats.
NOT_FORMATS = {"_cli", "_cxml", "_viewer_assets", "mcp", "physicsnemo"}


def format_subpackages() -> list[str]:
    """Every subpackage of the package that calls ``register_format``."""
    names = []
    for init in sorted(PACKAGE.glob("*/__init__.py")):
        directory = init.parent
        if directory.name in NOT_FORMATS:
            continue
        if any(
            "register_format" in path.read_text(encoding="utf-8")
            for path in directory.glob("*.py")
        ):
            names.append(directory.name)
    return names


def observe() -> tuple[dict[str, str], dict[str, list[str]]]:
    """``(format or writer name -> subpackage, extension -> subpackages)``."""
    import meshioplusplus
    from meshioplusplus import _helpers

    package = meshioplusplus.__name__
    names: dict[str, str] = {}
    extensions: dict[str, list[str]] = {}
    original = _helpers.register_format

    def recording(format_name, exts, reader, writer_map):
        caller = sys._getframe(1).f_globals["__name__"]
        module = caller[len(package) + 1 :].split(".")[0]
        for name in (format_name, *writer_map):
            if names.setdefault(name, module) != module:
                raise SystemExit(
                    f"{name!r} is registered by both {names[name]!r} and {module!r}"
                )
        for ext in exts:
            owners = extensions.setdefault(ext, [])
            if module not in owners:
                owners.append(module)
        return original(format_name, exts, reader, writer_map)

    _helpers.register_format = recording
    try:
        for module in format_subpackages():
            importlib.import_module(f"{package}.{module}")
    finally:
        _helpers.register_format = original
    return names, extensions


def render() -> str:
    names, extensions = observe()
    modules = sorted(set(names.values()))
    out = [
        '"""Which format subpackage registers which format and extension.',
        "",
        "Generated by ``tools/gen_format_table.py``: do not edit by hand.",
        "``_helpers`` imports only the subpackages a read or write needs, and",
        "this is how it finds them without importing the others first.",
        '"""',
        "",
        "# Every format and writer name -> the subpackage that registers it.",
        "FORMAT_MODULES = {",
    ]
    out += [f'    "{name}": "{names[name]}",' for name in sorted(names)]
    out += [
        "}",
        "",
        "# Every extension -> the subpackages that register it, in registration order.",
        "EXTENSION_MODULES = {",
    ]
    for ext in sorted(extensions):
        mods = ", ".join(f'"{m}"' for m in extensions[ext])
        # No trailing comma after two or more, or black explodes the tuple.
        out.append(f'    "{ext}": ({mods}{"," if len(extensions[ext]) == 1 else ""}),')
    out += ["}", "", "# Every format subpackage.", "ALL_MODULES = ("]
    out += [f'    "{m}",' for m in modules]
    out += [")", ""]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if out of date")
    args = parser.parse_args()
    text = render()
    current = TABLE.read_text(encoding="utf-8") if TABLE.exists() else ""
    if args.check:
        if current != text:
            print(
                f"{TABLE.relative_to(ROOT)} is out of date: run {Path(__file__).name}"
            )
            return 1
        return 0
    TABLE.write_text(text, encoding="utf-8")
    print(f"wrote {TABLE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
