#!/usr/bin/env python3
"""Regenerate ``tests/python/meshes/nastran/optistruct_mixed.fem``.

A HyperMesh/OptiStruct-style deck written here, not by meshio++, so the
Nastran reader is never only checked against its own writer. It exercises:

* an I/O-options and case-control section before ``BEGIN BULK``;
* small-field, large-field (``GRID*``) and free-field (comma) cards, a
  compressed-exponent coordinate (``5.-1``), explicit ``+`` continuations;
* a 20-node ``CHEXA`` and a 10-node ``CTETRA`` in Nastran node order (spelled
  out edge by edge below), a ``CQUAD4`` with a THETA field, a ``CBAR`` with an
  orientation vector;
* HyperMesh components: ``$HMMOVE`` with a ``THRU`` range and single ids,
  ``$HMNAME COMP`` after the elements, a component found through its property
  id only (no ``$HMMOVE``), and a named but empty one;
* OptiStruct ``SET`` cards (a GRID set with ``THRU`` named by ``$HMSET``, a
  free-field ELEM set without a name);
* optimization, contact and unsupported-element cards the reader must skip
  with a warning (``DESVAR``, ``DRESP1``, ``TIE``, ``CONTACT``, ``CONM2``).

Grid ids are ten times the point index plus ten, so id and index differ.

    python tools/gen_optistruct_fixture.py
"""

import pathlib

OUT = (
    pathlib.Path(__file__).resolve().parent.parent
    / "tests"
    / "python"
    / "meshes"
    / "nastran"
    / "optistruct_mixed.fem"
)

HEX = [
    (0, 0, 0),
    (1, 0, 0),
    (1, 1, 0),
    (0, 1, 0),
    (0, 0, 1),
    (1, 0, 1),
    (1, 1, 1),
    (0, 1, 1),
]
APEX = (0, 0, 2)
# CHEXA mid-edges in Nastran order: bottom ring, vertical edges, top ring.
HEX_EDGES = [
    (0, 1),
    (1, 2),
    (2, 3),
    (3, 0),
    (0, 4),
    (1, 5),
    (2, 6),
    (3, 7),
    (4, 5),
    (5, 6),
    (6, 7),
    (7, 4),
]

points = []


def grid(xyz):
    """The grid id of a point, adding it on first use."""
    xyz = tuple(float(c) for c in xyz)
    if xyz not in points:
        points.append(xyz)
    return 10 * (points.index(xyz) + 1)


def mid(a, b):
    return tuple((p + q) / 2 for p, q in zip(a, b))


hexa = [grid(c) for c in HEX] + [grid(mid(HEX[a], HEX[b])) for a, b in HEX_EDGES]
tet_corners = [HEX[4], HEX[5], HEX[7], APEX]
# CTETRA mid-edges: 1-2, 2-3, 3-1, 1-4, 2-4, 3-4.
TET_EDGES = [(0, 1), (1, 2), (2, 0), (0, 3), (1, 3), (2, 3)]
tetra = [grid(c) for c in tet_corners] + [
    grid(mid(tet_corners[a], tet_corners[b])) for a, b in TET_EDGES
]
quad = [grid(HEX[k]) for k in (0, 3, 2, 1)]
tria = [grid(HEX[4]), grid(HEX[5]), grid(APEX)]
bar = [grid(HEX[0]), grid(APEX)]


def small(fields):
    return "".join(f"{f:<8}" for f in fields).rstrip() + "\n"


def fixed_real(x):
    if x == 0.5:
        return "5.-1"  # Nastran compressed exponent
    return f"{x:.1f}"


def card_with_continuations(name, eid, pid, nodes):
    """Small-field element card, eight fields per line after the first six."""
    lines = []
    head = [name, eid, pid] + nodes[:6]
    rest = nodes[6:]
    k = 1
    while True:
        marker = f"+C{eid}{k}" if rest else ""
        lines.append("".join(f"{f:<8}" for f in head) + marker)
        if not rest:
            break
        head = [marker] + rest[:8]
        rest = rest[8:]
        k += 1
    return "\n".join(line.rstrip() for line in lines) + "\n"


out = []
out.append("$$ OptiStruct-style deck generated by tools/gen_optistruct_fixture.py\n")
out.append("OUTPUT,HM,ALL\n")
out.append("OUTPUT,H3D,ALL\n")
out.append("SUBCASE       1\n")
out.append("  LABEL loadstep1\n")
out.append("  SPC =        1\n")
out.append("BEGIN BULK\n")
out.append("$$\n$$  GRID Data\n$$\n")
for k, (x, y, z) in enumerate(points):
    gid = 10 * (k + 1)
    if k % 3 == 0:
        out.append(f"GRID*   {gid:<16d}{'':16s}{x:>16.8E}{y:>16.8E}\n")
        out.append(f"*       {z:>16.8E}\n")
    elif k % 3 == 1:
        out.append(small(["GRID", gid, ""] + [fixed_real(c) for c in (x, y, z)]))
    else:
        out.append(f"GRID,{gid},,{x!r},{y!r},{z!r}\n")
out.append("$$\n$$  Elements\n$$\n")
out.append(card_with_continuations("CHEXA", 100, 1, hexa))
out.append(card_with_continuations("CTETRA", 101, 1, tetra))
out.append(small(["CQUAD4", 200, 2] + quad + ["0.0"]))
out.append("CTRIA3,202,2," + ",".join(str(g) for g in tria) + "\n")
out.append(small(["CBAR", 300, 7] + bar + ["0.0", "1.0", "0.0"]))
out.append("$\n$HMMOVE       10\n")
out.append("$            100THRU         101\n")
out.append("$\n$HMMOVE       20\n")
out.append("$            200     202\n")
out.append("$$\n$$  Properties, materials, optimization, contact\n$$\n")
out.append(small(["PSOLID", 1, 1]))
out.append(small(["PSHELL", 2, 1, "0.1", 1]))
out.append(small(["PBAR", 7, 1, "0.01"]))
out.append(small(["MAT1", 1, "210000.", "", "0.3"]))
out.append(small(["CONM2", 400, bar[1], "", "2.5"]))
out.append(small(["DESVAR", 1, "T1", "0.1", "0.01", "1.0"]))
out.append(small(["DRESP1", 1, "MASS", "MASS"]))
out.append(small(["DRESP1", 2, "COMP", "COMP"]))
out.append(small(["TIE", 1, "", 1, 2]))
out.append(small(["CONTACT", 2, "FREEZE", 1, 2]))
out.append('$\n$HMSET        1        1 "base_nodes" 18\n')
out.append('$HMSETTYPE         1 "non-ordered" 18\n')
g0, g1 = grid(HEX[0]), grid(HEX[1])
out.append(small(["SET", 1, "GRID", "LIST", g0, "THRU", g1]))
out.append("SET,2,ELEM,LIST,100,200,\n")
out.append("+,300\n")
out.append("$$\n$$  HyperMesh name and color information for generic components\n$$\n")
out.append('$HMNAME COMP                  10"solids"\n')
out.append("$HWCOLOR COMP                 10       4\n")
out.append('$HMNAME COMP                  20"shells"\n')
out.append("$HWCOLOR COMP                 20       5\n")
out.append('$HMNAME COMP                  30"beams"        7 "PBAR" 4\n')
out.append('$HMNAME COMP                  40"empty"\n')
out.append("ENDDATA\n")

OUT.write_text("".join(out))
print(f"wrote {OUT} ({len(points)} grids)")
