"""Render the format conformance matrix into the docs, or re-observe it.

``tests/python/conformance_spec.py`` declares what every writable format keeps
through a write and a read (its ``SPEC``); ``test_conformance.py`` checks the
declarations against reality. This script turns the declarations into
``doc/conformance.md`` and the "Round trip" column of ``doc/formats.md``::

    python tools/gen_conformance_table.py            # rewrite both pages
    python tools/gen_conformance_table.py --check    # exit 1 if either is stale
    python tools/gen_conformance_table.py --observe [fmt ...]
                                                     # print observed SPEC entries

``--observe`` is how the table is refreshed after an intended change: paste
the printed entries over the old ones, review the diff, keep each ``note``.
"""

from __future__ import annotations

import argparse
import pathlib
import pprint
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "tests" / "python"))

import conformance_spec as cs  # noqa: E402

CONFORMANCE_MD = REPO / "doc" / "conformance.md"
FORMATS_MD = REPO / "doc" / "formats.md"

_CELL_SYMBOL = {"exact": "✓", "reordered": "↻", "lost": "✗", "?": "?"}
_SHORT = {
    "vertex": "vtx",
    "line": "line",
    "triangle": "tri",
    "quad": "quad",
    "tetra": "tet",
    "hexahedron": "hex",
    "wedge": "wdg",
    "pyramid": "pyr",
}


def _cell(outcome):
    if outcome is None:
        return ""
    if outcome.startswith("as "):
        return "→ " + "+".join(_SHORT.get(t, t) for t in outcome[3:].split("+"))
    return _CELL_SYMBOL.get(outcome, outcome)


def _data(entries):
    out = []
    for name, outcome in entries.items():
        if outcome == "missing":
            continue
        out.append(f"`{name}` {outcome}")
    return ", ".join(out) if out else "—"


def _anchor(fmt):
    return re.sub(r"[^a-z0-9-]", "-", fmt.lower())


def summary(fmt: str) -> str:
    """The compact cell of the "Round trip" column in doc/formats.md."""
    spec = cs.SPEC.get(fmt)
    if spec is None:
        return "—"
    link = f"(./conformance.md#{_anchor(fmt)})"
    err = spec.get("error")
    if err == "write-only":
        return f"[write-only]{link}"
    if err and "points" not in spec:
        return f"[fails]{link}"
    kept = sum(1 for o in spec["cells"].values() if o in ("exact", "reordered"))
    parts = [f"{kept}/{len(cs.CELL_TYPES)} cells"]
    data = "".join(
        letter
        for letter, key in (("P", "point_data"), ("C", "cell_data"))
        if any(o != "missing" for o in spec[key].values())
    )
    if spec["field_data"]:
        data += "F"
    parts.append(f"data {data}" if data else "no data")
    if spec["regions"]:
        parts.append("regions " + "".join(k[0].upper() for k in spec["regions"]))
    return f"[{' · '.join(parts)}]{link}"


def render_conformance() -> str:
    head = [
        "# Format conformance",
        "",
        "What every writable format keeps when meshio++ writes a file and reads it back. One canonical mesh — one cell of each linear type, float64/int32/vector point data, float64/int32 cell data, field data and one point, cell and side region — goes through `write` and `read` for each format, and the observed result must match the declaration in `tests/python/conformance_spec.py` exactly: `tests/python/test_conformance.py` fails when a format starts losing something *or* starts keeping something, so this page cannot drift from the code. It is generated by `tools/gen_conformance_table.py`; do not edit it by hand.",
        "",
        "The per-format pages say *why* something is lost; this page says *what*. Region membership is checked in depth by the [region round-trip matrix](./regions.md), and node-ordering by [node ordering](./node_ordering.md).",
        "",
        "## Legend",
        "",
        "- **Cell columns**: ✓ the cell comes back node for node; ↻ the same nodes in another order; → *types* written as other cells (a quad as two triangles, a volume as its skin); ✗ silently dropped when written next to the other types; blank: the writer refuses the type on its own.",
        "- **Points**: `exact`; `approx` (within 1e-6, single precision); `2d` (z dropped); `subset` (the points of dropped cells are gone, the rest exact); `none` (a format with no geometry); `changed`.",
        "- **Point data / cell data**: the arrays that come back, with the dtype read (`~`: values only approximately equal; `?`: shape or values changed). `p_f64`/`c_f64` are float64, `p_i32`/`c_i32` int32, `p_vec` a float64 3-vector.",
        "- **F**: the field-data array `fd` survives. **Regions**: the kinds (point, cell, side) whose region comes back under its own name.",
        "",
        "## Matrix",
        "",
    ]
    cols = [_SHORT[t] for t in cs.CELL_TYPES]
    lines = [
        "| Format | "
        + " | ".join(cols)
        + " | Points | Point data | Cell data | F | Regions |",
        "|---" * (len(cols) + 6) + "|",
    ]
    notes = []
    for fmt in sorted(cs.SPEC, key=str.lower):
        spec = cs.SPEC[fmt]
        name = f'<span id="{_anchor(fmt)}">`{fmt}`</span>'
        err = spec.get("error")
        if err == "write-only":
            lines.append(
                f"| {name} | "
                + " | ".join("" for _ in cols)
                + " | write-only | | | | |"
            )
        elif err and "points" not in spec:
            cells = " | ".join(
                _cell(spec.get("cells", {}).get(t)) for t in cs.CELL_TYPES
            )
            lines.append(f"| {name} | {cells} | fails: `{err}` | | | | |")
        else:
            cells = " | ".join(_cell(spec["cells"].get(t)) for t in cs.CELL_TYPES)
            regions = ", ".join(spec["regions"]) or "—"
            lines.append(
                f"| {name} | {cells} | {spec['points']} | {_data(spec['point_data'])} | "
                f"{_data(spec['cell_data'])} | {'✓' if spec['field_data'] else '—'} | {regions} |"
            )
        if spec.get("note"):
            notes.append(f"- **`{fmt}`**: {spec['note']}")
    body = head + lines
    if notes:
        body += ["", "## Notes", ""] + notes
    return "\n".join(body) + "\n"


def render_formats(text: str) -> str:
    """doc/formats.md with its format table's "Round trip" column refreshed."""
    out = []
    for line in text.split("\n"):
        if line.startswith("| Format name |"):
            cells = [c.strip() for c in line.strip("|").split("|")]
            if "Round trip" not in cells:
                cells.append("Round trip")
            out.append("| " + " | ".join(cells) + " |")
            continue
        if re.match(r"^\|-+\|", line) and out and out[-1].startswith("| Format name |"):
            n = out[-1].count("|") - 1
            out.append("|" + "---|" * n)
            continue
        m = re.match(r"^\| \[`([^`]+)`\]", line)
        if m and out and _in_format_table(out):
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            width = out_header_width(out)
            cells = cells[: width - 1]
            while len(cells) < width - 1:
                cells.append("")
            cells.append(summary(m.group(1)))
            out.append("| " + " | ".join(cells) + " |")
            continue
        out.append(line)
    return "\n".join(out)


def _in_format_table(out):
    for line in reversed(out):
        if line.startswith("| Format name |"):
            return True
        if not line.startswith("|"):
            return False
    return False


def out_header_width(out):
    for line in reversed(out):
        if line.startswith("| Format name |"):
            return line.count("|") - 1
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--observe", nargs="*", metavar="FORMAT")
    args = ap.parse_args(argv)
    if args.observe is not None:
        import meshioplusplus

        fmts = args.observe or meshioplusplus.formats()["writable"]
        import signal

        def _timeout(*_):
            raise TimeoutError

        signal.signal(signal.SIGALRM, _timeout)
        for fmt in fmts:
            signal.alarm(120)  # a reader that never returns is a finding too
            try:
                obs = cs.observe(fmt)
            except TimeoutError:
                obs = {"error": "timeout"}
            finally:
                signal.alarm(0)
            note = cs.SPEC.get(fmt, {}).get("note")
            if note:
                obs["note"] = note
            print(f"    {fmt!r}: {pprint.pformat(obs, width=88, sort_dicts=False)},")
        return 0
    want = {
        CONFORMANCE_MD: render_conformance(),
        FORMATS_MD: render_formats(FORMATS_MD.read_text(encoding="utf-8")),
    }
    stale = [
        p
        for p, text in want.items()
        if not p.exists() or p.read_text(encoding="utf-8") != text
    ]
    if args.check:
        for p in stale:
            print(f"stale: {p.relative_to(REPO)} (run tools/gen_conformance_table.py)")
        return 1 if stale else 0
    for p in stale:
        p.write_text(want[p], encoding="utf-8")
        print(f"wrote {p.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
